README.md, pywren/pywren_ibm_cloud/wren.py
Commits f38422d 4c17730:
- Fixed an issue in get_result() method when futures is not a list. Now it ensures that futures is always a list before call the corresponding internal _get_result()/_get_all_results() method.
Commit bc1d3a1:
- Modified default runtime name in readme and link to the list of included packages in order to match the official IBM documentation.
work with …
=> Fixed issue in get_result() method

runtime/deploy_runtime
Now it is possible to run **./deploy_runtime** script with **update** command. Then, when PyWren code is updated, there is no need to recreate all the runtime from scratch. The command just updates the PyWren code of the action.
For example:
`./deploy_runtime update jsampe/pywren-dlib-runtime:3.6`
by me, under the same open …
=> Added udpate command in deploy_runtime script

pywren/pywren_ibm_cloud/wrenutil.py
minor fix
when using list() method on a string, python splits it by chars instead of making an one element list object
=> bucket streams split wrong fix

pywren/pywren_ibm_cloud/partitioner.py, pywren/pywren_ibm_cloud/plots.py, pywren/pywren_ibm_cloud/wren.py, pywren/pywren_ibm_cloud/wrenutil.py
Created built-in method that generates execution timeline plots in a specified folder.
How to use?
Map:
```
pw = pywren.ibm_cf_executor()
futures = pw.map(my_map_function, range(200))
result pw.get_result()
pw.create_timeline_plots(dst='/home/jsampe/desktop', name='testmap')
```
Map-Reduce: (need to return statuses from reduce, for now)
```
pw = pywren.ibm_cf_executor()
futures = pw.map(my_map_function, range(200), my_reduce_function)
result = pw.get_result()
pw.create_timeline_plots(dst='/home/jsampe/desktop', name='testmapreduce',
result['run_statuses'], result['invoke_statuses'] )
```
have the right to submit it under the …
=> Add support to generate execution timeline plots

pywren/pywren_ibm_cloud/action/jobrunner.py, pywren/pywren_ibm_cloud/runtime.py, runtime/deploy_runtime
Now, `docker` command is not required to be installed when running `./deploy_runtime clone ...` …
=> Updated deploy_runtime script

README.md, pywren/pywren_ibm_cloud/cf_connector.py, pywren/pywren_ibm_cloud/storage/backends/cos.py, runtime/deploy_runtime, runtime/extract_modules.py
Now deploy_runtime script allows to clone any docker image built from any Python version. Previously, the command could only clone images of the same version of local Python.
(c) The …
=> Updated deploy_runtime script, clone command

pywren/ibmcf/default_config.yaml.template, pywren/pywren_ibm_cloud/action/jobrunner.py, pywren/pywren_ibm_cloud/action/wrenhandler.py, pywren/pywren_ibm_cloud/cf_connector.py, pywren/pywren_ibm_cloud/executor.py, pywren/pywren_ibm_cloud/future.py, pywren/pywren_ibm_cloud/invokers.py, pywren/pywren_ibm_cloud/partitioner.py, pywren/pywren_ibm_cloud/plots.py, pywren/pywren_ibm_cloud/wait.py, pywren/pywren_ibm_cloud/wren.py, pywren/pywren_ibm_cloud/wrenconfig.py, pywren/pywren_ibm_cloud/wrenutil.py, pywren/setup.py, runtime/requirements.txt
By using this service: https://console.bluemix.net/catalog/services/cloudamqp, it is possible to quickly track the functions that have finished.
Add the AMQP_URL in the config file:
```
rabbitmq: 
amqp_url : <AMQP_URL>
```
This feature is integrated in the `pw.monitor()` method.
To activate it, use: `pw = pywren.ibm_cf_executor(use_rabbitmq=True)`
If the rabbitmq config is not in the config file, the feature is ignored by PyWren, even if `use_rabbitmq=True`
of my knowledge, is covered under an appropriate …
=> Enable rabbitmq to track finished function activations

install_pywren.sh, pywren/pywren_ibm_cloud/partitioner.py
Installation script now supports PyWren version as an input parameter, for example:
`./install_pywren 1.0.2`
or
`curl -fsSL "https://git.io/fhe9X" | sh /dev/stdin 1.0.2`
(c) The contribution …
=> Installation script to support PW version as a parameter

pywren/pywren_ibm_cloud/wrenlogging.py
for debugging without boto3 logs:
```python
pw = pywren.ibm_cf_executor(log_level='DEBUG')
```
for debugging with boto3 logs:
```python
pw = pywren.ibm_cf_executor(log_level='DEBUG_BOTO3')
```
=> added boto3 logging option

pywren/pywren_ibm_cloud/partitioner.py
currently, partitioner gets keys' heads from storage and it takes too long cause it is done sequentially.
improved this by adding ThreadPool support, so partitioner will work in parallel now. …
=> improve partitioner's time

docs/configuration.md, pywren_ibm_cloud/action/handler.py, pywren_ibm_cloud/cf_connector.py, pywren_ibm_cloud/storage/backends/cos.py, pywren_ibm_cloud/wrenconfig.py
This patch allows to set COS private_endpoint into the config.
It is optional, so if not set, PyWren will continue to use the public endpoint.
If set, all functions will use private_endpoint …
=> Added COS private_endpoint parameter

pywren_ibm_cloud/action/__main__.py, pywren_ibm_cloud/action/handler.py, pywren_ibm_cloud/action/jobrunner.py, pywren_ibm_cloud/future.py, pywren_ibm_cloud/libs/ibm_cf/cf_connector.py, pywren_ibm_cloud/libs/ibm_iam/iam_connector.py, pywren_ibm_cloud/libs/tblib/__init__.py, pywren_ibm_cloud/wait.py, pywren_ibm_cloud/wren.py
1. In this patch I improved the exception management when a function produces an exception so that PyWren only prints the exception traceback of the function, instead of the full traceback from the local pywren code. For example, currently when an exception is produced within a function, pywren shows all of this traceback:
```
Traceback (most recent call last):
File "examples/rabbitmq_monitor.py", line 51, in <module>
results = pw.get_result()
File "/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/wren.py", line 387, in get_result
WAIT_DUR_SEC=WAIT_DUR_SEC)
File "/home/josep/data/eclipse-workspace/pywren-ibm-cloud/pywren_ibm_cloud/wren.py", line 323, in monitor
pbar=pbar, THREADPOOL_SIZE=THREADPOOL_SIZE, WAIT_DUR_SEC=WAIT_DUR_SEC)
File …
```
=> Improved Function exception management

pywren_ibm_cloud/action/handler.py, pywren_ibm_cloud/executor.py
with this minor change we can know from which function the future came from and its runtime memory.
I found it useful for diagnosing PyWren results. …
=> Add function_name to future's status

README.md, examples/cloudobject.py, pywren_ibm_cloud/__init__.py, pywren_ibm_cloud/executor.py, pywren_ibm_cloud/job/job.py, pywren_ibm_cloud/job/partitioner.py, pywren_ibm_cloud/runtime/function_handler/handler.py, pywren_ibm_cloud/runtime/function_handler/jobrunner.py, pywren_ibm_cloud/storage/internal_storage.py, pywren_ibm_cloud/storage/storage_utils.py
This patch integrates the CloudObject class. 
To operate with CloudObjects, it adds 2 methods in internal_storage class  in order to put temporary data from a function and get this data from another function in a transparent way.
Writing **internal_storage** as a parameter of the function automatically creates an instance of it, allowing to execute the new `internal_storage.put_object()` and` internal_storage.get_object()` methods. The `put_object()` method returns a CloudObject instance.
Example:
```
import pywren_ibm_cloud as pywren
def my_function_put(text, internal_storage):
co1 = internal_storage.put_object('Temp object test 1: {}'.format(text, ))
co2 = internal_storage.put_object('Temp object test 2: {}'.format(text, ))
return [co1, co2]
def my_function_get(co, internal_storage): …
```
=> Integrated CloudObject

runtime/ibm_cf/Dockerfile.gdal.conda
Add a new docker image into runtime, for support of processing satellite imagery pipeline with Cloud Function + Pywren.
=> add new docker image for satellite imagery

config/README.md, config/config_template.yaml, pywren_ibm_cloud/__init__.py, pywren_ibm_cloud/compute/backends/docker/config.py, pywren_ibm_cloud/compute/backends/docker/docker.py, pywren_ibm_cloud/compute/backends/ibm_cf/config.py, pywren_ibm_cloud/compute/backends/knative/config.py, pywren_ibm_cloud/compute/backends/localhost/config.py, pywren_ibm_cloud/compute/backends/localhost/localhost.py, pywren_ibm_cloud/compute/compute.py, pywren_ibm_cloud/config.py, pywren_ibm_cloud/executor.py, pywren_ibm_cloud/invoker.py, pywren_ibm_cloud/job/job.py, pywren_ibm_cloud/runtime/function_handler/handler.py, pywren_ibm_cloud/runtime/utils.py, pywren_ibm_cloud/storage/storage.py, pywren_ibm_cloud/storage/utils.py, pywren_ibm_cloud/tests.py, pywren_ibm_cloud/wait/wait_rabbitmq.py, runtime/docker/entry_point.py
Now, with the new invoker and this patch, it is possible to set the desired maximum number of concurrent workers. It can be set in any executor, for example:
`pw =  pywren.ibm_cf_executor(workers=500)`
This executor results on this:
This can be also set in the config file, in the pywren section.
By default, if not set, it uses the max available concurrency (1200 for CF)
Other Changes:
- Docs updated
- Fixed issue #228 
license and I have the …
=> Added the concept of workers

runtime/knative/Dockerfile
Currently long running actions fail on knative due to short gunicorn timeout. This PR resolves it by setting timeout same as in HTTP request:
https://github.com/pywren/pywren-ibm-cloud/blob/master/pywren_ibm_cloud/compute/backends/knative/knative.py#L523
permitted to …
=> Setting 10 minutes timeout to the webserver

CHANGELOG.md, examples/cloudobject.py, examples/context_manager.py, pywren_ibm_cloud/cli/runtime/utils.py, pywren_ibm_cloud/cli/utils.py, pywren_ibm_cloud/config.py, pywren_ibm_cloud/executor.py, pywren_ibm_cloud/function/jobrunner.py, pywren_ibm_cloud/job/__init__.py, pywren_ibm_cloud/job/job.py, pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py, pywren_ibm_cloud/storage/storage.py, pywren_ibm_cloud/storage/utils.py, pywren_ibm_cloud/tests.py, pywren_ibm_cloud/utils.py
Following this thread: #289 
Changed location of the methods used to put/get cloudobjects. Now they are in `ibm_cos` param. `internal_storage` param is no longer supported in functions:
```
internal_storage.put_object() --> ibm_cos.put_cobject()
internal_storage.get_object() --> ibm_cos.get_cobject()
```
`pw.clean()` method is extended to support:
- pw.clean() (without args) internally managed futures and related cloudobjects are deleted.
- pw.clean(fs=futures_list), only the given futures are deleted.
- pw.clean(cs=cloudobjects_list) only the given cloudobjects are deleted.
- pw.clean(fs=futures_list, cs=cloudobjects_list) both are deleted.
Added context manager in PyWren executor. Now it supports:
```python
iterdata = [1, 2, 3, 4]
with pywren.ibm_cf_executor() as pw: …
```
=> Improved cloudobjects management

pywren_ibm_cloud/function/jobrunner.py
This feature is to allow custom code execution before user function and after user function, thus, cleanly separating between initialization and finalization specific to the execution environment (e.g., database connection initialization/finalization).
permitted to …
=> Added option to run custom code before jobrunner run

pywren_ibm_cloud/compute/backends/common/common_utils.py
Minor fix for a bug when PyWren creates a runtime
it.
(d) I …
=> Minor fix for a bug when PyWren creates a runtime 

pywren_ibm_cloud/tests.py, pywren_ibm_cloud/utils.py
If the argument to a Pywren function is a list or a tuple then it is not handled correctly in `verify_args`. This PR provides a fix and a test that fails without the fix.
(c) The contribution …
=> Fix case where function argument is a list or tuple.

CHANGELOG.md, pywren_ibm_cloud/compute/backends/localhost/localhost.py
Fixes https://github.com/metaspace2020/pywren-annotation-pipeline/issues/80
`Process.daemon` prevents subprocesses from creating new child processes. LocalhostBackend's worker processes are used to invoke user code, and user code may want to create child processes for performance reasons, or to launch external tools. Therefore, it's undesirable to spawn these worker processes with the `daemon` flag.
There is a side effect: Daemon processes are supposedly automatically killed during Python shutdown when the parent process exits, and removing the daemon flag removes this nice automatic cleanup behavior. To fix this, I added extra code to clean up any remaining worker processes when Python shuts down.
This change is not needed for the codepath that uses `Threads`s, because `Thread.daemon` …
=> Fix localhost subprocesses

docs/ibm_vpc.md, pywren_ibm_cloud/compute/backends/docker/config.py, pywren_ibm_cloud/compute/backends/docker/docker.py, pywren_ibm_cloud/compute/backends/docker/entry_point.py, pywren_ibm_cloud/compute/compute.py, pywren_ibm_cloud/compute/utils.py, pywren_ibm_cloud/config.py, pywren_ibm_cloud/executor.py, pywren_ibm_cloud/libs/clients/ibm_vpc/config.py, pywren_ibm_cloud/libs/clients/ibm_vpc/ibm_vpc.py
In current implementation, dismantle procedure invoked from host may not be triggered.
For example, in case of network connectivity loss or exception.
- added keeper thread in pywren_ibm_cloud/compute/backends/docker/entry_point.py
- code refactoring to remove remote_agent out of the docker backend layer completely
- refactored code to avoid duplication
work with modifications, …
=> Added auto_dismantle call from runtime container

setup.py
Enum34 is a compatibility library to allow Python <= 3.3 to use the `enum` library that is included with Python >= 3.4. Lithops now [requires Python >= 3.5](https://github.com/lithops-cloud/lithops/blob/master/setup.py#L56), so the compatibility library is no longer needed. Furthermore, it can create issues with pip, because enum34 actually overrides the native enum library and doesn't include newer features from Python 3.6 such as `enum.IntFlag`.
of my knowledge, is covered under an appropriate open …
=> Remove unnecessary enum34 dependency

lithops/standalone/backends/ibm_vpc/ibm_vpc.py
Currently the StandaloneBackend constructor is crashing on attempt to instantiate IBMIAMTokenManager with wrong signature
person …
=> Fixing crashing StandaloneBackend constructor bug

CHANGELOG.md, lithops/invokers.py, lithops/libs/cloudpickle/__init__.py, lithops/libs/cloudpickle/cloudpickle_160.py, lithops/libs/cloudpickle/cloudpickle_160_fast.py, lithops/libs/cloudpickle/compat.py
Add cloudpickle 1.6.0 lib only for python>=3.8
Python<3.8 will continue using current cloudpickle 1.2.2 …
=> Add cloudpickle 1.6.0

runtime/ibm_cf/Dockerfile.python38
updating gevent version to fix the broken runtime issue
currently the runtime create fails on:
stderr: <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject"
by me, under the same open source license (unless I …
=> The current runtime fails on gevent error

lithops/executors.py, lithops/standalone/standalone.py
starts the VM and validates that proxy service is running
in case proxy service not running installs it
currently supported for standalone executor only …
=> Added init() to executors API

lithops/multiprocessing/managers.py
Avoid [SyntaxWarnings on Python >= 3.8](https://docs.python.org/3/whatsnew/3.8.html#porting-to-python-3-8).
% `python3.8` or `python3.9`
```
>>> () is ()
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
Also, this logic seems a bit dangerous because this will only match if `args` is an __empty tuple__.  `[] != ()` so this will not match against an empty list, set, or other iterator.
I would have written: `if args:`
license …
=> Avoid syntax warning on Python >= 3.8

lithops/executors.py
- Fix description of the argument `map_iterdata` in `executors map_reduce` method.
person who certified (a), (b) or (c) and I have …
=> Fix map_iterdata description in map_reduce method.

lithops/config.py, lithops/invokers.py, lithops/scripts/cli.py, lithops/serverless/backends/gcp_functions/gcp_functions.py, lithops/serverless/backends/ibm_cf/ibm_cf.py, lithops/standalone/backends/ibm_vpc/ibm_vpc.py, lithops/storage/backends/ibm_cos/ibm_cos.py, lithops/util/__init__.py, lithops/worker/jobrunner.py
- Improved logging when creating a new custom runtime for GCP Functions
- Refactor IBMTokenManager (removed from `utils.__init__.py` since IBMTokenManager imports `ibm_botocore` and this module is not available by default in other backends).
- Fixed CLI `lithops runtime create` command (Added `--mode` flag to select execution mode).
work with modifications, whether created in whole …
=> GCP Functions Backend create custom runtime update

lithops/scripts/cli.py
The runtime create command currently broken. It is missing required 'mode' parameter. This PR resolves the issue
person who …
=> Fixes failing runtime create bug

lithops/serverless/backends/openwhisk/openwhisk.py
Fixes 2 bugs in the openwhisk create runtime
1. the call for _generate_runtime_meta been missing mandatory memory argument
2. _generate_runtime_meta invokes an action to get its runtime details (e.g. installed modules) and obviously can't be called before the runtime (action) created. it should be called only after the action created in the openwhisk.
work with modifications, whether …
=> fixes broken openwhisk runtime create

config/compute/ibm_cf.md, config/storage/aws_s3.md, config/storage/ibm_cos.md
- Add some minor corrections to docs.
- In the config file, `storage_bucket` is compulsory when using AWS S3 and IBM COS, isn't it? I've added the key in both documentations.
(c) The …
=> Docs minor correction

lithops/util/ssh_client.py
I sometimes get stalls while starting an IBM VPC VM. This is what the logs looked like (Note: I added `print(ex)` to the exception handler in `StandaloneHandler._is_proxy_ready` so I could see why it was infinitely looping):
```
Lithops v2.2.11 init for IBM Virtual Private Cloud - Host: 149.81.167.108 - Region: eu-de
ExecutorID c27521-8 | JobID A000 - Selected Runtime: metaspace2020/metaspace-lithops:1.8.1 
ExecutorID c27521-8 | JobID A000 - Uploading function and data - Total: 656.0B
'SSHClient' object has no attribute '_create_client'
ExecutorID c27521-8 - Starting VM instance
'SSHClient' object has no attribute '_create_client'
'SSHClient' object has no attribute '_create_client'
'SSHClient' object has no attribute '_create_client'
'SSHClient' object has no attribute '_create_client' …
```
=> Fix call to SSHClient.create_client

CHANGELOG.md, lithops/storage/backends/localhost/localhost.py, lithops/tests.py
* Support passing file-like objects to `put_object` for streaming uploads
* The `1024*1024` parameter to `shutil.copyfileobj(data, f, 1024*1024)` determines chunk size. It may warrant further tuning, but I know that the default value (16kB) definitely causes performance issues.
* Support `head_bucket` and `head_object` functions
* Fixed empty parent directory deletion when deleting objects. The previous behavior was to delete a single parent directory, even if it was non-empty. Now it can delete multiple layers of empty directories, but only if they are actually empty.
* Made `list_keys`/`list_objects` behavior consistent with COS-style backends. 
* Passing `prefix='foo'` will now match a files called `foo`, `foo0`, `foo123`, etc.
* Changed `list_keys` to not use case-insensitive `glob`. …
=> Localhost Storage fixes/improvements

docs/api_multiprocessing.md, examples/multiprocessing/buffered_queue.py, examples/multiprocessing/queue_poll.py, examples/multiprocessing/simple_queue.py, lithops/multiprocessing/__init__.py, lithops/multiprocessing/context.py, lithops/multiprocessing/popen_cloud.py, lithops/multiprocessing/queues.py
- Fixed `from lithops.multiprocessing import get_context`
- Removed feeder thread for `Queue`: This was a feature inherited from original multiprocessing module using Processes. With Redis and serverless functions it's not necessary and only adds bugs and unexpected behaviors.
by me, under the same open source license …
=> [multiprocessing] Queue and get_context fix

config/compute/ibm_vpc.md, config/config_template.yaml, lithops/executors.py, lithops/standalone/backends/ibm_vpc/config.py, lithops/standalone/backends/ibm_vpc/ibm_vpc.py, lithops/standalone/proxy.py, lithops/standalone/standalone.py
* New StandaloneExecutor create() API added to provision new temporary VM in IBM VPC
* New delete_on_dismantle boolean flag added under config ibm_vpc section. In case True, the VM instance deleted instead of stopped by default
* Used ibm_vpc python SDK instead. We should consider to change the start/stop to use sdk as well
usage example:
```
import lithops
def hello(name):
print("in hello")
return 'Hello {}!'.format(name)
if __name__ == '__main__':
fexec = lithops.StandaloneExecutor(log_level='DEBUG')
fexec.create()  #provisions vm instance in ibm vpc
fexec.call_async(hello, 'Worlds')
print(fexec.get_result())
```
A number of new parameters required under ibm_vpc section in order to provision VMs in IBM VPC:
* security_group_id: <SECURITY_GROUP_ID>
* subnet_id: <SUBNET_ID>
* key_id: …
=> Provide ability to automatically create and delete VM instances

lithops/libs/openwhisk/client.py
When configuration contains date fields, like `version     : 2020-12-01` the OpenWhisk client will fail to serialize the payload in the invoke method. The exception would be "date time is not serializable json python". To overcome the issue I added "default=str" to the json.dumps . This will enable to use default str for the fields that failed to be serializable
work with …
=> [openwhisk client] support date in json payload

docs/functions.md, lithops/multiprocessing/pool.py
In the multiprocessing api, `map` and `map_async` had the same behaivor as `starmap`. That was because lithops core unpacks params when they come from a tuple, a dict or a list (I believe that list unpacking is deprecated).
This caused the lithops api to behave differently than the native python api. For example, this code:
``` python
def f(x):
return x[0]
Pool().map(f, [(1,2), (3,4)])
```
In the native multiprocessing returns [1,3], but using lithops it throws a "TypeError: too many positional arguments".
This PR tries to solve that problem with `map` and `map_async` functions, and also fixes a minor error from the docs related to the unpacking. 
(a) The contribution was created in whole or in …
=> Encapsulate map params on multiprocessing api 

lithops/standalone/standalone.py, lithops/util/ssh_client.py
Update `wait_backend_ready()` method to detect a more accurate time when the VM is ready to receive commands, and avoid possible ssh errors #516 
(c) The contribution was provided directly to …
=> update wait_backend_ready method

lithops/standalone/standalone.py
`standalone.create_runtime()` method must always install the proxy, even if the proxy is already present and running in the VM …
=> install proxy in create_runtime

lithops/localhost/localhost.py
Some Docker runtimes I use have both Python2.7 and Python3.
Normally, the entrypoint "python" defaults to Python2.7 for backwards compatibility reasons.
This patch forces localhost docker execution to use "python3" as the container entrypoint.
permitted to submit under …
=> Force docker localhost executor to use python3

config/compute/aliyun_fc.md, config/compute/aws_lambda.md, config/compute/azure_fa.md, config/compute/code_engine.md, config/compute/gcp_functions.md, config/compute/ibm_cf.md, config/compute/knative.md, config/compute/openwhisk.md, config/config_template.yaml, lithops/serverless/backends/aliyun_fc/config.py, lithops/serverless/backends/aws_lambda/config.py, lithops/serverless/backends/azure_fa/config.py, lithops/serverless/backends/cloudrun/config.py, lithops/serverless/backends/code_engine/config.py, lithops/serverless/backends/gcp_functions/config.py, lithops/serverless/backends/ibm_cf/config.py, lithops/serverless/backends/knative/config.py, lithops/serverless/backends/openwhisk/config.py, runtime/code_engine/Dockerfile, runtime/code_engine/requirements.txt
Currently, the runtime name in serverless mode can only be introduced in the serverless section of the config. With this patch, the runtime name can also be introduced in the backend section …
=> Allow to introduce the runtime at backend level

CHANGELOG.md, lithops/executors.py, lithops/job/job.py, lithops/serverless/backends/aliyun_fc/config.py, lithops/serverless/backends/aws_lambda/config.py, lithops/serverless/backends/azure_fa/config.py, lithops/serverless/backends/cloudrun/config.py, lithops/serverless/backends/code_engine/config.py, lithops/serverless/backends/gcp_functions/config.py, lithops/serverless/backends/ibm_cf/config.py, lithops/serverless/backends/knative/config.py, lithops/serverless/backends/openwhisk/config.py
Currently, `invoke_pool_threads` can only be configured in runtime. This patch allows to introduce this variable in the config, backend level. #521  …
=> Allow invoke_pool_threads to be set in config

config/README.md, config/config_template.yaml, lithops/standalone/proxy.py, lithops/standalone/standalone.py, lithops/util/ssh_client.py
Reduce number of ssh connections during installation process
Move `ping` and `get_preinstalls` from ssh to http since they do not contain critical information
Move `run_job` method from ssh to http, using an encription key to encrypt the payload
**ACTIONS REQUIRED:**
**- Open port 8080 in your VPC security group**
**- Add `use_http: true` in the `standalone` section of the config**
**- Add `encription_key: < ENCRYPITON_KEY>` in the `standalone` section of the config**
of my knowledge, is covered under an …
=> [Standalone] Reduce number of ssh connections

lithops/serverless/backends/ibm_cf/ibm_cf.py
Now in IBM Cloud Functions backend, each function package contains the first 5 digits of the API key. This patch changes those digits to the first 4 digits of the API key password instead of user (first 4 digits after `:`).
This is useful when more than one user are sharing the same namespace. Now, when one user does `lithops clean`, all functions of all users are deleted. The API key user is shared among all namespace users, but the password isn't. This way, each package is unique identified to the user who created it, and when they execute `lithops clean` only those packages are deleted.
have the right to submit it under the …
=> [IBM CF] Change user_key to API-key pass instead of user

lithops/util/joblib/lithops_backend.py
Since #584, the joblib backend was broken and the example from https://github.com/lithops-cloud/applications/tree/master/sklearn didn't work. 
That is because lithops.multiprocessing map function was a starmap and #584 fixed that inconsistency with the native multiprocessing. 
The lithops' joblib backend was programmed with the old behavior in mind.
work with modifications, whether …
=> Fix joblib backend

lithops/util/joblib/lithops_backend.py
The joblib backend allways creates a Pool in the same way, without passing arguments to the Pool constructor. This PR allows to pass arguments to the Pool constructor in the joblib backend.
(c) …
=> Pass arguments to Pool in joblib backend

lithops/config.py, lithops/executors.py, lithops/wait/func.py
This patch allows to specify a different backend for the input data to process, for example:
```python
def extract_color(obj):
print(obj.key)
iterdata = 'cos://josep-datasets'
fexec= lithops.FunctionExecutor(backend="localhost", storage="localhost", log_level='DEBUG')
fexec.map(extract_color, [iterdata], timeout=5)
fexec.get_result()
```
work with modifications, whether created in …
=> allow different backend in input data

CHANGELOG.md, config/compute/azure_batch.md, config/storage/ibm_cos.md, lithops/constants.py, lithops/invokers.py, lithops/serverless/backends/aliyun_fc/entry_point.py, lithops/serverless/backends/aws_lambda/entry_point.py, lithops/serverless/backends/azure_functions/azure_functions.py, lithops/serverless/backends/azure_functions/config.py, lithops/serverless/backends/azure_functions/entry_point.py, lithops/serverless/backends/code_engine/entry_point.py, lithops/serverless/backends/gcp_cloudrun/entry_point.py, lithops/serverless/backends/gcp_functions/entry_point.py, lithops/serverless/backends/ibm_cf/entry_point.py, lithops/serverless/backends/k8s/entry_point.py, lithops/serverless/backends/k8s/k8s.py, lithops/serverless/backends/knative/entry_point.py, lithops/serverless/backends/openwhisk/entry_point.py, lithops/version.py, lithops/worker/handler.py, lithops/worker/taskrunner.py, lithops/worker/utils.py
Currently, when using the `chunksize` parameter, each task in the worker creates 1 storage client and makes 2 calls to the storage backend to get the function and the data. These number of requests increase linearly based on `chunksize`, so if for example `chunksize=100`, each worker will create 100 storage clients and make a total of 200 requests to the storage backend.
With this patch, the storage client is created _per worker_ and not _per task_, so with this if `chunksize=100` (or any other value), the worker will always create only 1 client, and make 2 requests to the object storage to get the function and the data.
have the …
=> get function and data only once in worker

lithops/scripts/cli.py
`ServerlessHandler` constructor args changed in #613 (storage_config was replaced by an instance of InternalStorage directly). The CLI script, where instances of `ServerlessHandler` are created, wasn't updated. This patch fixes this issue.
permitted to submit under a …
=> Fix CLI issue

CHANGELOG.md, lithops/serverless/backends/aliyun_fc/config.py, lithops/serverless/backends/aws_lambda/config.py, lithops/serverless/backends/azure_functions/config.py, lithops/serverless/backends/code_engine/config.py, lithops/serverless/backends/gcp_cloudrun/config.py, lithops/serverless/backends/gcp_functions/config.py, lithops/serverless/backends/k8s/config.py, lithops/serverless/backends/knative/config.py, runtime/aliyun_fc/requirements.txt, runtime/aws_lambda/Dockerfile.python38, runtime/aws_lambda/requirements.txt, runtime/code_engine/requirements.txt, runtime/gcp_cloudrun/Dockerfile, runtime/gcp_cloudrun/Dockerfile.conda, runtime/gcp_functions/requirements.txt, runtime/ibm_cf/Dockerfile.slim, runtime/ibm_cf/requirements.txt, runtime/knative/Dockerfile, runtime/knative/Dockerfile.conda
After some tests I could verify that `pika==0.13.1` is no longer necessary and users can use any newer version
person who …
=> Delete pika=0.13.1 dependency

lithops/serverless/backends/aws_lambda/aws_lambda.py, lithops/serverless/backends/aws_lambda/config.py, runtime/aws_lambda/README.md
Changes:
- Pre-built Lambda layer containing numpy and scipy is no longer added to lithops function. The layer that is built at runtime creation that contains lithops dependencies already has numpy (since it's a direct dependency for Pandas), so numpy and other modules were duplicated. Very little space was left for other additional modules (unzipped layers cannot weight >250MB), which made difficult to add additional layer modules. Now there is more space for extra layer modules.
- `aws` cli is no longer required for building container runtimes. It was used to log-in to ECR, but now the access token is retrieved using `boto3`.
Fixes:
- Fixed issue that prevented building container runtimes that had an image tag.
- Container runtimes that used the `latest` image tag now are correctly …
=> [AWS Lambda] Lambda backend update and fixes

lithops/utils.py
- Return an empty byte string when EOF instead of raising an exception
- Avoid multiple "discarding first partial row" logic when the read() method is called multiple times
(c) The contribution …
=> Fix wrapper streaming body

lithops/multiprocessing/pool.py
Fix exception not raised when waiting for pool apply result.
it.
(d) …
=> [multiprocessing] Fix exception not raised when waiting for pool apply result

CHANGELOG.md, config/compute/aws_lambda.md, lithops/serverless/backends/aws_lambda/aws_lambda.py, lithops/serverless/backends/aws_lambda/config.py, runtime/aws_lambda/Dockerfile.python38
- Dockerfile for container runtimes updated. `awslambdaric` is no longer pinned (https://github.com/lithops-cloud/lithops/pull/665).
- Added `account_id` in config parameters. It will be used if present instead of querying STS (https://github.com/lithops-cloud/lithops/issues/661).
- Updated AWS Lambda configuration docs. Added a JSON ready to use policy for copy-paste instead of manual selection of policies.
license and I have the right under …
=> [AWS Lambda] Update Dockerfile & config parameters

CHANGELOG.md, README.md, config/README.md, config/config_template.yaml, docs/function_chaining.md, lithops/executors.py, lithops/future.py, lithops/job/serialize.py, lithops/monitor.py, lithops/serverless/backends/k8s/entry_point.py, lithops/standalone/master.py, lithops/standalone/standalone.py, lithops/utils.py, lithops/wait.py, lithops/worker/jobrunner.py
This PR enables the function chaining pattern in the Futures API. This is especially useful when the output of one function invocation is the input of another function invocation. With this, results from one function invocation are never downloaded to the local client, but directly get from the next function, unless you explicitly call the `get_result()` method.
With this, you can code with Lithops like this:
```python
import lithops
def my_func1(x):
return x*2, 5
def my_func2(x, y):
return x+y
iterdata = [1, 2, 3]
fexec = lithops.FunctionExecutor()
res = fexec.map(my_func1, iterdata).map(my_func2).get_result()
print(res)
```
have …
=> Add function chaining pattern in the Futures API

lithops/serverless/backends/code_engine/code_engine.py, lithops/version.py
Sometimes the "preinstalls" pod takes more time to start than the time given by Lithops, causing the job to fail.
Sometimes the "preinstalls" pod fails due an incorrect built, causing Lithops to fail for no apparent/concrete reason.
This PR replaces the COS static retrying mechanism by the k8s dynamic monitor API to detect the extracted "preinstalled modules" file, which prevents both previous possible failures.
license and I have the right …
=> [CE] Use k8s api to monitor the 'preinstalls' pod

CHANGELOG.md, lithops/serverless/backends/aws_lambda/aws_lambda.py, lithops/serverless/backends/aws_lambda/config.py
- Uses public pre-built layer from [Klayers](https://github.com/keithrozario/Klayers) for numpy instead of using binaries compiled locally. Fixes issue in #694, where a host using Windows or Mac OS will use compiled numpy Windows/MacOS while lambda uses Amazon Linux. …
=> [AWS Lambda] Get pre-built numpy layer instead of compile locally

CHANGELOG.md, lithops/executors.py, lithops/invokers.py, lithops/job/job.py, lithops/monitor.py, lithops/scripts/cleaner.py, lithops/standalone/master.py, lithops/standalone/worker.py, lithops/storage/storage.py, lithops/version.py, lithops/wait.py, lithops/worker/invoker.py, lithops/worker/status.py
With this patch, performance of multiple `call_async()` invoked with a `for loop` is equivalent to a single `map()` call
- There is now one monitor per `FunctionExecutor` instead of one monitor per jobs (this substantially reduces COS Requests when there are multiple jobs in the same executor)
- Created a cache for runtime meta
- Improve `lithops.cleaner` performance (this substantially reduces COS Requests when there are multiple jobs in the same executor)
Execution example previous this patch:
Execution example with this patch:
(b) The contribution is based upon …
=> Improve performance and efficiency of call_async() calls

.github/workflows/nightly_build.yml, .github/workflows/on_pr.yml
Seems workflows also run on all users forks (master branch). Users fork do not need to run these workflows. Moreover, github workflows quota is limited per user and this can consume all the users quota.
Couldn't test it yet since it is not merged, but this should avoid running these workflows on users forks.
by me, under …
=> Avoid running workflows on users forks

config/README.md, lithops/localhost/localhost.py, lithops/standalone/backends/ibm_vpc/config.py, lithops/standalone/backends/ibm_vpc/ibm_vpc.py, lithops/standalone/keeper.py, lithops/standalone/master.py, lithops/standalone/standalone.py, lithops/standalone/worker.py
when `standalone.exec_mode == reuse`:
- If no running workers detected
- spawn required number of workers
- run tasks on workers
- else
- run all tasks on existing workers
- if less workers than tasks, same worker used for multiple tasks
- keeper keeps workers untill soft_dismantle_timeout reached
by me, under the same open …
=> Adding VM reuse option for vpc standalone backend

lithops/standalone/keeper.py
Fixing a bug introduced in #754 
bug: master keeper  never detects that job finished and never switches to soft_dismantle_timeout …
=> Fixing bug introduced in keeper

CHANGELOG.md, lithops/serverless/backends/aws_lambda/aws_lambda.py, lithops/serverless/backends/aws_lambda/build_layer.py, lithops/serverless/backends/aws_lambda/config.py
- Moved layer build to a lambda, solves OS related errors when compiling libraries and numpy is added to the dependencies (no need to use third party layers) (#745)
- Adjusted new memory configurations (128 MB minimum and removed 64 MB increments check)
- Add support for Python3.9 (#746)
by me, under the same open source …
=> [AWS Lambda] Moved layer build to lambda -- Add support for Python 3.9

docs/api_futures.md, examples/map_reduce.py, lithops/executors.py, lithops/wait.py
This patch makes the reduce function spawning in map_reduce() more flexible: Now it is possible to spawn the reducer immediately (**ALWAYS**), when one of the map functions finishes its execution (**ANY_COMPLETED**), or when all the map functions finished their executions (**ALL_COMPLETED**).
In the future, this will allow to specify a percentage of number of completed map functions before spawning the reduce function. For example: when 80% of the map functions are completed, spawn the reducer.
of my …
=> Make reduce function spawning in map_reduce() more flexible

lithops/standalone/backends/ibm_vpc/ibm_vpc.py
After master instance deleted it may take some time before its
boot volume get deleted. 
It may cause an exception on next master provision attempt due to current volume naming convention that is based on master name. …
=> Add random suffix to volume name

lithops/standalone/backends/ibm_vpc/ibm_vpc.py
VSI instances auto-started when created. Currently, after VM provisioned, it is also triggered to start which can result in exception in some cases. …
=> Don't start vsi instance after provisioned

CHANGELOG.md, docs/source/compute_config/aws_ec2.md, docs/source/supported_clouds.rst, lithops/localhost/localhost.py, lithops/standalone/backends/aws_ec2/config.py, lithops/standalone/master.py, lithops/standalone/standalone.py, lithops/standalone/utils.py, lithops/standalone/worker.py
- Cancel all tasks running on workers on ctrl-c or exception. Currently tasks are never canceled and run until the end in the workers.
- Allow master VM to ask worker VMs if they are free or bussy. This substantially improves the time needed by the master VM to know the available free workers
by me, under the same open …
=> [Standalone] Cancel all tasks running on workers on ctrl-c or exception

lithops/standalone/backends/ibm_vpc/ibm_vpc.py, lithops/standalone/master.py, lithops/standalone/standalone.py
Currently, when user has master VM already running and uses same VPC with different config.yaml having different ssh key than the one initially used with master initialization, lithops will print some weird messages, like
`oops, unhandled type 3 (‘unimplemented’)`
and will hang for very log time before failing.
by me, under …
=> Validate master VM public ssh key is a pair of used private ssh key

lithops/executors.py
This patch solves error when trying to plot when passing an instance of FuturesList returned by map to FunctionExecutor.plot.
Steps to reproduce:
```python
import lithops
def echo(msg):
return msg
fexec = lithops.FunctionExecutor()
fs = fexec.map(echo, ['hello', 'hello', 'hello'])  # type of fs is FuturesList
fexec.get_result()
fexec.plot(fs=fs)
```
```
Traceback (most recent call last):
File "/home/aitor/Projects/lithops-github/lithops/examples/plottest.py", line 17, in <module>
fexec.plot(fs=fs2, dst='plots/'+fs2[0].executor_id+'_'+fs2[0].job_id)
File "/home/aitor/Projects/lithops-github/lithops/lithops/executors.py", line 504, in plot
ftrs_to_plot = [f for f in ftrs if (f.success or f.done) and not f.error]
File "/home/aitor/Projects/lithops-github/lithops/lithops/executors.py", line …
```
=> Fix plot function when passing a FuturesList instance

lithops/standalone/backends/ibm_vpc/ibm_vpc.py
Instead of using `ssh-keygen` binary from shell now using paramiko python module to validate ssh key pair
resolves #859 
person …
=> validating ssh pair programmatically

lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- Convert ssh key filename to abspath to prevent `[Errno 2] No such file or directory: '~/.ssh/id_rsa'`
- Raise an exception if the ssh key does not exist …
=> [Standalone] convert ssh key to abspath and raise an exception if not exists

lithops/standalone/backends/ibm_vpc/ibm_vpc.py
Added missing support for validation of multiple ssh keys
resolves #859 …
=> support multiple public keys in vm

CHANGELOG.md, lithops/scripts/cli.py, lithops/storage/backends/aliyun_oss/aliyun_oss.py, lithops/storage/backends/aws_s3/aws_s3.py, lithops/storage/backends/azure_storage/azure_storage.py, lithops/storage/backends/ceph/ceph.py, lithops/storage/backends/gcp_storage/gcp_storage.py, lithops/storage/backends/gcsfs/gcsfs.py, lithops/storage/backends/ibm_cos/ibm_cos.py, lithops/storage/backends/infinispan/infinispan.py, lithops/storage/backends/infinispan_hotrod/infinispan_hotrod.py, lithops/storage/backends/localhost/localhost.py, lithops/storage/backends/minio/minio.py, lithops/storage/backends/redis/redis.py, lithops/storage/backends/swift/swift.py, lithops/storage/storage.py, lithops/util/ssh_client.py
This enables much faster uploads and downloads of files to/from the storage backend when using the `lithops storage put ...` or `lithops storage get ..`. commands
(c) The contribution was …
=> Add download_file() and upload_file() methods to Storage API

docs/source/compute_config/gcp_cloudrun.md, docs/source/compute_config/gcp_functions.md, docs/source/storage_config/gcp_storage.md
In the documents for Google Cloud Run and Google Cloud Functions it is stated that the lithops config file requires the name of the Google Cloud project given by the user. However, this is not true and will result in an error 404 when trying to run code with this config. Instead it is required to enter the ID given to the project by Google Cloud. I changed the affected doc-files to refer to this project id instead of the project name.
license …
=> Changed docs for Google cloud backend refering to id instead of name

lithops/serverless/backends/gcp_cloudrun/cloudrun.py, lithops/serverless/backends/gcp_cloudrun/config.py
The variable runtime_cpu was in some places referred to as runtime_cpus, which caused errors. This pull request fixes them by changing occurrences of runtime_cpus to runtime_cpu.
(c) The …
=> Fixed wrong variable name runtime_cpus for gcp_cloudrun

CHANGELOG.md, docs/source/compute_config/knative.md, examples/map.py, lithops/config.py, lithops/constants.py, lithops/invokers.py, lithops/localhost/localhost.py, lithops/serverless/backends/code_engine/code_engine.py, lithops/serverless/backends/code_engine/config.py, lithops/serverless/backends/k8s/config.py, lithops/serverless/backends/k8s/k8s.py, lithops/serverless/backends/knative/config.py, lithops/serverless/backends/knative/knative.py, lithops/serverless/serverless.py, lithops/standalone/standalone.py, lithops/utils.py
Kubernetes backends (kubernetes, code_engine and knative) needs docker installed in the local machine to build the default runtime if no runtime is provided in config. In this sense, all these backends (config.py files) contains a block of logic that checks whether docker is installed or not. This is a limitation when using the `lithops cli`, since for almost all the `lithops cli` commands it is not needed to check whether docker is installed or not.
This patch moves the logic that checks if docker is installed within a method that it only called during the invocation. …
=> Load runtime data only on invocation

lithops/executors.py
Windows doesn't allow `:` in path files. Job summary csv file name contains `:`, so `FunctionExecutor.job_summary()` fails on windows hosts. This patch replaces `:` with `-` in the file name to avoid this problem. …
=> Fix job summary for windows hosts

lithops/job/serialize.py
The `inspect` built-in python module has the following [code](https://github.com/python/cpython/blob/2fe016fbba7c3b8ec9c759221175971a3f235a68/Lib/inspect.py#L1554):
``` python
def getclosurevars(func):
if ismethod(func):
func = func.__func__
if not isfunction(func):
raise TypeError("{!r} is not a Python function".format(func))
...
```
And the function `getclosurevars` is [used in lithops](https://github.com/lithops-cloud/lithops/blob/d2d2a83527671d64a445411bc47843b308095b87/lithops/job/serialize.py#L138) with each element of `worklist` in [`SerializeIndependent._module_inspect`](https://github.com/lithops-cloud/lithops/blob/d2d2a83527671d64a445411bc47843b308095b87/lithops/job/serialize.py#L95).
This PR checks each method appended to `worklist` to be sure that its `__func__` are python …
=> Check that methods have functions in serialize.py

CHANGELOG.md, docs/source/compute_config/ibm_vpc.md, lithops/standalone/backends/ibm_vpc/config.py, lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- make image_id in ibm vpc mandatory
- Tested and working with ubuntu 22.04 …
=> make image_id in ibm vpc mandatory

lithops/localhost/localhost.py
#1014 broke docker localhost backend, this patch fixes it. Some path references were hard-coded and did not reflect the new path for localhost in tmp. …
=> Fix tmp lithops path for docker localhost backend

lithops/executors.py, lithops/job/job.py
This change allows additional arguments to be passed to the reduce function.
For example:
```python
import lithops
args = [  # Init list of parameters for Lithops
(1, 2),  # Args for function1
(3, 4),  # Args for function2
(5, 6),  # Args for function3
]  # End list of parameters for Lithops
def my_function(x, y, extra_param):
print(f"Extra param: {extra_param}")
return x + y
def my_reduce_function(results, extra_param):
print(f"Extra param: {extra_param}")
return sum(results)
if __name__ == "__main__":
fexec = lithops.FunctionExecutor()
fexec.map_reduce(my_function, args, my_reduce_function, extra_args=(1,), extra_args_reduce=(2,))
print(fexec.get_result())
```
(a) The contribution was created …
=> Add additional arguments to pass to the reduce function in map_reduce()

CHANGELOG.md, lithops/job/job.py
Job creation only checks the size of the first element in `iterdata`.
I modified this check, and now checks all the elements in `iterdata`. In the case of an `iterdata` with large elements, the `all` function would return `False` immediately after checking the first element, so there shouldn't be any real performance degradation. 
What do you think @JosepSampe ?
work with …
=> Check size of each iterdata element

CHANGELOG.md, lithops/worker/jobrunner.py
=> [MapReduce] Make 'results' variable name not mandatory

CHANGELOG.md, lithops/serverless/backends/aws_lambda/config.py, setup.py
For https://github.com/lithops-cloud/lithops/issues/1132
Still need to be tested, but this should be enough …
=> [AWS Lambda] Allow Python3.11 runtimes

lithops/job/partitioner.py
Very small fix for the case that the iterdata passed to create_partitions consists of CloudObjects, which leads to a failure ".startswith" at lines 56 and 60  …
=> fix create_partitions() failure with CloudObject inputs

lithops/scripts/cli.py
Make sure these commands work when no config is provided, since the default standalone exec mode is the consume, and in the consume mode it is mandatory a VM id in the config
(c) The …
=> [CLI] Fix lithops image commands

CHANGELOG.md, config/config_template.yaml, docs/source/compute_config/aws_ec2.md, docs/source/compute_config/azure_vms.md, docs/source/compute_config/code_engine.md, docs/source/compute_config/ibm_vpc.md, docs/source/compute_config/knative.md, docs/source/compute_config/kubernetes.md, lithops/constants.py, lithops/scripts/cli.py
The main reason of this change is that the `reuse` mode does not need config at all in the backend section, while the `consume` mode requires more parameters, so it makes more sense to define `exec_mode: consume` when there are more parameters in the config, instead of having to explicit set `exec_mode: reuse` alone in the backend section of the config.
At the same time, the are some cli commands (`lithops clean`, `lithops worker list`, `lithops job list` , `lithops image build`) that don't work because of the current default `consume` mode. With this change, they will all work by default without "tricks" in the code.
have the …
=> [Standalone] Changed default mode of execution from 'consume' to 'reuse'

.github/workflows/functional_tests.yml, lithops/serverless/backends/aliyun_fc/config.py, lithops/serverless/backends/aws_lambda/config.py, lithops/serverless/backends/azure_containers/config.py, lithops/serverless/backends/azure_functions/config.py, lithops/serverless/backends/code_engine/config.py, lithops/serverless/backends/gcp_cloudrun/config.py, lithops/serverless/backends/gcp_functions/config.py, lithops/serverless/backends/k8s/config.py, lithops/serverless/backends/knative/config.py, lithops/serverless/backends/oracle_f/config.py
=> Update functional tests

lithops/scripts/cli.py, lithops/standalone/keeper.py, lithops/standalone/master.py, lithops/standalone/standalone.py, lithops/standalone/utils.py, lithops/standalone/worker.py
=> [CLI] Show worker creation timestamp and ttd in lithops worker list

CHANGELOG.md, docs/source/worker_granularity.rst, lithops/serverless/backends/aws_lambda/config.py, lithops/serverless/backends/gcp_functions/config.py, lithops/serverless/backends/ibm_cf/config.py, lithops/serverless/backends/openwhisk/config.py, lithops/standalone/master.py, runtime/openwhisk/Dockerfile.slim, setup.py
=> Add support for Python 3.12

lithops/storage/backends/gcp_storage/gcp_storage.py
This fixes the following warning:
```
PendingDeprecationWarning: Blob.download_as_string() is deprecated and will be removed in future. Use Blob.download_as_bytes() instead.
```
(c) The …
=> Fix deprecation warning in GCP storage for Blob.download_as_string()

CHANGELOG.md, docs/index.rst, docs/source/compute_backends.rst, docs/source/compute_config/aws_batch.md, docs/source/compute_config/aws_lambda.md, docs/source/compute_config/azure_vms.md, docs/source/compute_config/oracle_functions.md, docs/source/storage_config/aws_s3.md, lithops/serverless/backends/aws_batch/aws_batch.py, lithops/serverless/backends/aws_batch/config.py, lithops/serverless/backends/aws_lambda/aws_lambda.py, lithops/serverless/backends/aws_lambda/config.py, lithops/storage/backends/aliyun_oss/aliyun_oss.py, lithops/storage/backends/aliyun_oss/config.py, lithops/storage/backends/aws_s3/aws_s3.py, lithops/storage/backends/aws_s3/config.py, lithops/storage/backends/azure_storage/azure_storage.py, lithops/storage/backends/azure_storage/config.py, lithops/storage/backends/ceph/ceph.py, lithops/storage/backends/ceph/config.py, lithops/storage/backends/gcp_storage/config.py, lithops/storage/backends/gcp_storage/gcp_storage.py, lithops/storage/backends/ibm_cos/config.py, lithops/storage/backends/ibm_cos/ibm_cos.py, lithops/storage/backends/minio/config.py, lithops/storage/backends/minio/minio.py, lithops/storage/backends/oracle_oss/config.py, lithops/storage/backends/oracle_oss/oracle_oss.py, lithops/storage/backends/swift/swift.py, lithops/storage/storage.py
Part of https://github.com/lithops-cloud/lithops/issues/1293, #1295 
- [Storage] Move logic to create the bucket name inside the backend class
This previous change is required to allow:
- [AWS Lambda] Eliminate the need for access and secret keys in the configuration
- [AWS Batch] Eliminate the need for access and secret keys in the configuration
- [AWS S3] Eliminate the need for access and secret keys in the configuration
license and I have the …
=> [Storage] Move logic to create the bucket name inside the backend class

lithops/retries.py, lithops/tests/test_retries.py
Fixes #1289
This is a first draft - it still needs API doc and tests.
As noted in #1289 this uses wrappers around `ResponseFuture` and `FunctionExecutor`. I considered using subclasses, but that wasn't possible for `ResponseFuture` because `RetryingFuture` updates the underlying `ResponseFuture` for each retry. And `FunctionExecutor` already has subclasses (`LocalhostExecutor`, `ServerlessExecutor`, and `StandaloneExecutor`), so that wasn't possible either.
It might be possible to add the retry logic directly into the existing `ResponseFuture` and `FunctionExecutor` classes, but I'm not familiar enough with the internals, so I wasn't sure how easy that would be or if it's even desirable. @JosepSampe what do you think?
The current implementation in this PR also lacks some of the methods …
=> Add a mechanism to automatically retry failed tasks

.github/workflows/on_pull_request.yml, lithops/libs/multyvac/module_dependency.py, lithops/worker/jobrunner.py, lithops/worker/status.py
`distutils` library is deprecated on python 3.12
it. …
=> [Jobrunner] deprectate distutils

lithops/job/serialize.py, lithops/tests/functions.py, lithops/tests/test_call_async.py, lithops/tests/test_map_reduce.py, lithops/tests/test_storage.py
=> Fix serialization bug which triggers side effects on dynamic attributes

docs/source/compute_config/aws_batch.md, docs/source/compute_config/aws_ec2.md, docs/source/compute_config/aws_lambda.md, docs/source/storage_config/aws_s3.md, docs/source/storage_config/ceph.md, docs/source/storage_config/minio.md, setup.py
The `boto3` package is not needed unless you're using AWS, so this moves it from the base installation to an extra package, installable using `pip install lithops[aws]`. This is inline with GCP and Azure, for example. …
=> Move boto3 package into `lithops[aws]` extra

CHANGELOG.md, lithops/worker/utils.py
=> [Worker] Fix potential issue that can appear during `func_obj` loading from cache

.github/workflows/functional_tests.yml, .github/workflows/on_pull_request.yml, lithops/localhost/v2/localhost.py, lithops/worker/jobrunner.py, lithops/worker/status.py
=> Fix some potential issues

CHANGELOG.md, docs/source/compute_config/aws_batch.md, lithops/serverless/backends/aws_batch/aws_batch.py, lithops/serverless/backends/aws_batch/config.py
=> [AWS Batch] Update resource limits

docs/source/compute_config/ibm_cf.md, docs/source/compute_config/knative.md, docs/source/compute_config/kubernetes.md, docs/source/compute_config/kubernetes_rabbitmq.md, docs/source/storage_config/ibm_cos.md, setup.py
=> Add an 'ibm' extra package

runtime/gcp_cloudrun/Dockerfile, runtime/gcp_cloudrun/Dockerfile.conda
Closes #1382
@JosepSampe though we only discussed `--timeout` in the linked issue, I also included `--workers $CONCURRENCY` here as well, since that is included in the default GCP Cloud Run Dockerfile as well. If you'd prefer to handle that separately or in another way, of course happy to change it.
Thanks so much!
by me, …
=> Add timeout + concurrency options to gunicorn cmd in runtime/gcp_cloudrun dockerfiles

runtime/gcp_cloudrun/README.md
👋 All, thanks for the amazing project! I'm really enjoying getting to know it.
I was looking into making my own custom runtime for use with GCP Cloud Run and noticed this small typo in the docs, hopefully the fix is welcome and correct!
permitted to submit under a …
=> Fix typo (knative -> cloudrun) in custom GCP Cloud Run runtime docs

CHANGELOG.md, docs/source/compute_config/kubernetes.md, lithops/serverless/backends/k8s/config.py, lithops/serverless/backends/k8s/k8s.py
This pull request introduces a new configurable parameter, `master_timeout`, to the Kubernetes backend.
There may be jobs that last more than 10 minutes, which is the default master pod duration. Although the master pod is expected to restart automatically, there are cases where it does not restart or after restarting some jobs are lost, resulting in jobs shown in Lithops logs as **Pending**.
The new `master_timeout` parameter mitigates these issues by allowing to configure a suitable timeout based on the job requirements.
(b) The contribution is based upon previous work …
=> [k8s] Add configurable master pod timeout to Kubernetes backend

CHANGELOG.md, lithops/serverless/backends/k8s/entry_point.py
=> [k8s] Fixed bug between threads when there are multiple executions

lithops/future.py, lithops/tests/test_future.py
Closes https://github.com/lithops-cloud/lithops/issues/1396
As described in #1396, in `future.py`, the check `if self._call_output` fails (unintentionally) if the object assigned to `self._call_output` has an ambiguous truth value, as is the case for [pandas dataframes](https://github.com/pandas-dev/pandas/blob/e78ebd3f845c086af1d71c0604701ec49df97228/pandas/core/generic.py#L1494-L1499) and [numpy ndarrays](https://numpy.org/doc/stable/reference/arrays.ndarray.html#:~:text=Truth%2Dvalue%20testing%20of%20an%20array%20invokes%20ndarray.__bool__%2C%20which%20raises%20an%20error%20if%20the%20number%20of%20elements%20in%20the%20array%20is%20larger%20than%201%2C%20because%20the%20truth%20value%20of%20such%20arrays%20is%20ambiguous).
Changing this check to `if self._call_output is not None` …
=> Fix unintended failure of `if self._call_output` in future.py for objects with ambiguous truth values

lithops/storage/backends/aws_s3/aws_s3.py
Creating a bucket with the boto3 AWS S3 client may return a _InvalidLocationConstraint_ error, if we use the default value for an AWS region ("us-east-1") in the LocationConstraint parameter. More specifically:
`
ClientError: An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
`
This error has been previously reported:
[https://github.com/boto/boto3/issues/125](https://github.com/boto/boto3/issues/125)
[https://github.com/boto/boto3/issues/811](https://github.com/boto/boto3/issues/811)
I simply propose a quick fix that retries the operation without the LocationConstraint if the region is "us-east-1".
(a) The …
=> InvalidLocationConstraint error in AWS S3 handled.

CHANGELOG.md, lithops/invokers.py, lithops/monitor.py
=> [Invoker] Reduce threads in async FaaS Invoker and resolve token bucket issue

CHANGELOG.md, lithops/serverless/backends/code_engine/code_engine.py
=> [Code Engine] Allow to build the default runtime with Python 3.13

lithops/monitor.py
This PR fixes a race condition in the RabbitMQ job monitor.
The Rabbit Monitor has a main thread, which is left in a loop logging the status and checking future timeouts with 2 second sleeps, and a daemon thread consuming from Rabbit.
If the consumer thread  finds all futures completed after processing a message, it will stop  consuming. However, the main thread may still be in a 2 second sleep, which creates a window for the executor to add more futures to monitor (the executor checks the state of the main thread). Just that the consumer thread has already stopped, so those futures will stay pending indefinitely. This can easily happen in a map_reduce call when all map functions end closely together.
This PR basically flips the threads' responsibilities. The main Monitor thread is the …
=> Fix race condition in RMQ Monitor

lithops/serverless/backends/gcp_functions/gcp_functions.py
Instead of polling the function resource (which can return 404), update the deployment logic
to poll the long-running operation returned by the create() method
More information about operation polling for gcp [here](https://cloud.google.com/resource-manager/reference/rest/v1/operations/get)
by me, under the same open source …
=> Refactor: poll long-running operations for GCP Function deployment

lithops/scripts/cli.py
This PR fixes CLI **lithops storage list** error as discussed in issue #1430 …
=> [CLI] Fix storage list error

lithops/storage/storage.py
=> [Storage] Update documentation for list_objects

docs/source/compute_config/azure_vms.md, docs/source/compute_config/kubernetes.md, docs/source/configuration.rst, setup.py
=> [SETUP] [docs] Remove duplicated 'tblib' setup requirement. Update documentation by fixing typos.
