lithops-cloud/lithops

- README.md
- pywren/requirements.txt
>  Updated readme and requirements

- README.md
- docs/multiple_parameters.md
- pywren/pywren_ibm_cloud/wren.py
> Fix in map function. Updated readme.

- pywren/pywren_ibm_cloud/cf_connector.py
- pywren/pywren_ibm_cloud/invokers.py
- pywren/pywren_ibm_cloud/wren.py
> Improved fault tolerance mechanism in the invocation phase

- pywren/pywren_ibm_cloud/cf_connector.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/future.py
- pywren/pywren_ibm_cloud/invokers.py
- pywren/pywren_ibm_cloud/wren.py
- pywren/pywren_ibm_cloud/wrenhandler.py
- pywren/pywren_ibm_cloud/wrenutil.py
This patch enables the "remote invocation" mechanism which improves 5X the time needed to launch all the functions when the client machine is located in a remote network.
(c) The contribution …
> Improved function invocation phase time

- pywren/__main__.py
- pywren/deploy_pywren.sh
- pywren/pywren_ibm_cloud/cf_connector.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/future.py
- pywren/pywren_ibm_cloud/invokers.py
- pywren/pywren_ibm_cloud/jobrunner/jobrunner.py
- pywren/pywren_ibm_cloud/runtime.py
- pywren/pywren_ibm_cloud/serialize/cloudpickle/__init__.py
- pywren/pywren_ibm_cloud/serialize/cloudpickle/cloudpickle.py
- pywren/pywren_ibm_cloud/serialize/module_dependency.py
- pywren/pywren_ibm_cloud/serialize/serialize.py
- pywren/pywren_ibm_cloud/storage/cleaner.py
- pywren/pywren_ibm_cloud/wait.py
- pywren/pywren_ibm_cloud/wren.py
- pywren/pywren_ibm_cloud/wrenconfig.py
- pywren/pywren_ibm_cloud/wrenhandler.py
- pywren/pywren_ibm_cloud/wrenutil.py
Commit 7b6d936:
- Fixed a little issue when IBM-PyWren is used inside a function. 
- Changed few lines in wrenhandler.py which reduces in 2 seconds the function execution time.
- In wrenhandler.py, added a code that requests the IP of the VM where the function is executed. 
- Changed the logging of the funcions to DEBUG level. 
- Updated the cloudpickle package.
- Updated clean() method to be asynchronous to the main client code.
Commit 0bc5b33:
- Added an exception when a function reaches the memory limit.
Commit a6d1106:
- Changed the call_async() method in order to allow it to accept multiple call_async() calls before call pw.get_result(). Thus it is not necessary to create a new pw instance each time (This reduces total lines of code needed to run an experiment with multiple …
> IBM-PyWren update: exceptions, logging, deployment, etc.

- README.md
- pywren/pywren_ibm_cloud/wren.py
- pywren/requirements.txt
- runtime/Dockerfile
- runtime/README.md
- runtime/requirements.txt
> changed variable name: futures to ftrs

- examples/map_reduce_url.py
- pywren/pywren_ibm_cloud/executor.py
**object_url** parameter is not necessary.
it. …
> Fixed issue when processing a dataset from url

- pywren/ibmcf/default_config.yaml.template
- pywren/pywren_ibm_cloud/action/wrenhandler.py
- pywren/pywren_ibm_cloud/cf_connector.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/invokers.py
- pywren/pywren_ibm_cloud/wren.py
- pywren/pywren_ibm_cloud/wrenconfig.py
> Added retry logic

- examples/map_cos_bucket.py
- examples/map_reduce_cos_bucket.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/partitioner.py
- pywren/pywren_ibm_cloud/storage/backends/cos.py
- pywren/pywren_ibm_cloud/storage/backends/swift.py
- pywren/pywren_ibm_cloud/storage/cleaner.py
- pywren/pywren_ibm_cloud/storage/storage.py
- pywren/pywren_ibm_cloud/wren.py
- pywren/pywren_ibm_cloud/wrenutil.py
This pull request abstratcs COS logic into a generic method for being used both for map() and map_reduce() (Issue #26). Also, partitioner code has been moved to a new file, which will ease the implementation of issue #16.
There are no code additions in this pull request, just code moved to another places and code refactoring.
This pull request doesn not finish issue #26. However, it is a necessary step with enough changes to be a pull request. …
> Abstracted COS logic for map() and map_reduce() methods

- README.md
- test/data
- test/test.py
- test/testpywren.py
usage from Terminal:
python3 test.py		- full tests run
python3 test.py init	   - test init for COS
python3 test.py clean	  - test clean for COS
python3 test.py pywren	 - test pywren without COS
python3 test.py pywren_cos     - test pywren with COS
> add functional test script

- pywren/pywren_ibm_cloud/executor.py
> Raise exception when some activation fails

- pywren/pywren_ibm_cloud/action/jobrunner.py
- pywren/pywren_ibm_cloud/action/wrenhandler.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/libs/ps_mem/__init__.py
- pywren/pywren_ibm_cloud/libs/ps_mem/ps_mem.py
- pywren/pywren_ibm_cloud/storage/backends/cos.py
- pywren/pywren_ibm_cloud/storage/backends/swift.py
- pywren/pywren_ibm_cloud/wren.py
- pywren/pywren_ibm_cloud/wrenutil.py
To activate the log, add "extra_env={'SHOW_MEMORY_USAGE': True}" in the
parameters of any pywren method (call_async(), map(), map_reduce())
(c) The contribution was provided directly to me by …
> Added memory usage in action logs

- pywren/pywren_ibm_cloud/wren.py
> Fixed minor issue with pbar

- pywren/pywren_ibm_cloud/wren.py
- pywren/pywren_ibm_cloud/wrenutil.py
- runtime/deploy_runtime
> Increased max memory limit in deployment script

- README.md
- pywren/pywren_ibm_cloud/wrenutil.py
- test/testpywren.py
add more test options, now you can run a specific test function for debug comfort
> Test improve

- pywren/pywren_ibm_cloud/action/jobrunner.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/future.py
- pywren/pywren_ibm_cloud/storage/backends/cos.py
> Move to pickle package

- README.md
- install_pywren.sh
- pywren/pywren_ibm_cloud/runtime.py
- pywren/pywren_ibm_cloud/storage/backends/cos.py
- runtime/requirements.txt
> Fixed issue reusing tokens

- README.md
- install_pywren.sh
- pywren/pywren_ibm_cloud/deployutil.py
- pywren/setup.py
Added missing packages from https://github.com/pywren/pywren-ibm-cloud/issues/58
person who certified (a), (b) or (c) and I have …
> Added missing packages in setup.py

- README.md
- install_pywren.sh
- pywren/pywren_ibm_cloud/deployutil.py
To solve issue https://github.com/pywren/pywren-ibm-cloud/issues/72 …
> Install script to use latest release and not master branch

- pywren/ibmcf/default_config.yaml.template
- pywren/pywren_ibm_cloud/cf_connector.py
- pywren/pywren_ibm_cloud/deployutil.py
- pywren/pywren_ibm_cloud/wrenconfig.py
> action's memory and timeout are set from configuration file

- pywren/pywren_ibm_cloud/action/wrenhandler.py
- pywren/pywren_ibm_cloud/cf_connector.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/partitioner.py
- pywren/pywren_ibm_cloud/storage/backends/cos.py
- pywren/pywren_ibm_cloud/wren.py
This patch activates remote_invocation when the data comes from a COS bucket …
> remote_invocation when data comes from COS

- pywren/pywren_ibm_cloud/wren.py
Run multiple maps() in the same executor
it. …
> Run multiple maps() in the same executor

- pywren/pywren_ibm_cloud/cf_connector.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/invokers.py
- pywren/pywren_ibm_cloud/partitioner.py
- pywren/pywren_ibm_cloud/wren.py
- pywren/pywren_ibm_cloud/wrenutil.py
Added chunk_size parameter in map() method.
Added a wrapper to read data from COS and discard unnecessary data from threshold. …
> Improved partitioning

- examples/map_reduce_cos_bucket.py
- examples/map_reduce_cos_key.py
- examples/map_reduce_url.py
- pywren/pywren_ibm_cloud/partitioner.py
Fixed partitioner data wrapper
it. …
> Fixed partitioner data wrapper

- test/testpywren.py
improve tests and fix with last update
it. …
> Fixed tests to work with last partitioner update

- test/testpywren.py
> added dedicated chunk_size tests

- pywren/pywren_ibm_cloud/action/__main__.py
- pywren/pywren_ibm_cloud/action/jobrunner.py
- pywren/pywren_ibm_cloud/action/wrenhandler.py
- pywren/pywren_ibm_cloud/executor.py
- pywren/pywren_ibm_cloud/storage/backends/cos.py
- pywren/pywren_ibm_cloud/wren.py
- pywren/pywren_ibm_cloud/wrenconfig.py
- pywren/pywren_ibm_cloud/wrenlogging.py
This patch propagates the log_level to the functions.
it.
(d) I …
> log_level propagated to functions

- pywren/pywren_ibm_cloud/wren.py
> bug fix for map_reduce()

- pywren_ibm_cloud/__init__.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/wren.py
- runtime/README.md
- runtime/deploy_runtime
Fixes to ensure that all is working properly with the recent changes …
> Some fixes

- README.md
- pywren_ibm_cloud/cf_connector.py
- pywren_ibm_cloud/runtime/__init__.py
- pywren_ibm_cloud/runtime/deploy_utils.py
- runtime/deploy_runtime
- Readme updated explaining how to install PyWren in a notebook with the new pip package.
- Raise exception when the `zip` package is not installed in the machine, and then it is unable to create/clone/update a runtime …
> Updated readme

- pywren_ibm_cloud/executor.py
> Fix issue with log_level

- README.md
- docs/configuration.md
- docs/dev-installation.md
- docs/multiple_parameters.md
> Readme updated

- pywren_ibm_cloud/cf_connector.py
> Fix issue in cf_connector

- examples/monte_carlo/pi_estimation_using_monte_carlo_with_PyWren.ipynb
- examples/monte_carlo/stock_prediction_monte_carlo_with_PyWren.ipynb
> Updated notebooks

- pywren_ibm_cloud/action/handler.py
- pywren_ibm_cloud/action/jobrunner.py
- pywren_ibm_cloud/partitioner.py
- pywren_ibm_cloud/runtime/deploy_utils.py
- pywren_ibm_cloud/storage/backends/cos.py
- pywren_ibm_cloud/storage/backends/swift.py
- pywren_ibm_cloud/storage/storage.py
- pywren_ibm_cloud/storage/storage_utils.py
- pywren_ibm_cloud/wait.py
- pywren_ibm_cloud/wren.py
- pywren_ibm_cloud/wrenconfig.py
Commit 73b886a: Fixes issues when the COS token expires (https://github.com/metaspace2020/pywren-annotation-pipeline/issues/3)
Commit 4b7f609: Fixes issues when IBM-PyWren is used from a Windows Host (#118)
in …
> Fixed issues with COS token and Windows hosts

- pywren_ibm_cloud/action/handler.py
- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/utils.py
- pywren_ibm_cloud/wren.py
Fixed issue with 'signal' module on Windows hosts (Issue #121)
it. …
> Fixed issue with 'signal' module on Windows hosts

- pywren_ibm_cloud/plots.py
- pywren_ibm_cloud/wren.py
usage:
```python
pw.create_timeline_plots(dst_dir='cos://<bucket_name>/<dst_key>', dst_file_name='testmap')
```
person who …
> Add support to create PyWren's plots in COS

- config/default_config.yaml.template
- pywren_ibm_cloud/action/jobrunner.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/invokers.py
- pywren_ibm_cloud/libs/ibm_cf/cf_connector.py
- pywren_ibm_cloud/libs/ibm_iam/iam_connector.py
- pywren_ibm_cloud/plots.py
- pywren_ibm_cloud/runtime/deploy_utils.py
- pywren_ibm_cloud/storage/backends/cos.py
- pywren_ibm_cloud/storage/cleaner.py
- pywren_ibm_cloud/storage/storage.py
- pywren_ibm_cloud/testpywren.py
- pywren_ibm_cloud/wren.py
- pywren_ibm_cloud/wrenconfig.py
- Moved from **tornado** library to **requests** (issue #141)
- Put `imb_iam` config dictionary into `ibm_cos` dictionary. In this way, it is not necessary to pass a new parameter each time we want to start COS backend. …
> Changes in iam_connector

- README.md
- docs/configuration.md
- pywren_ibm_cloud/action/handler.py
- pywren_ibm_cloud/action/jobrunner.py
- pywren_ibm_cloud/future.py
- Reverted exception pickling issues
- Prevent false out-of-memory errors …
> Minor changes in pickle

- docs/dev-installation.md
- pywren_ibm_cloud/invokers.py
- pywren_ibm_cloud/runtime/deploy_utils.py
- pywren_ibm_cloud/runtime/metadata.py
- pywren_ibm_cloud/utils.py
- runtime/requirements.txt
- Added 'pywren_runtime update all' option: Now it is possible to run "update all" with `pywren_runtime` script in order to update the pywren code on all the deployed runtimes (Issue #151)
- Fixed docs (Issue #154)
- Fixed security alert with twisted
permitted to submit …
> Added 'pywren_runtime update all' option and Docs fixed

- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/wait.py
- pywren_ibm_cloud/wren.py
Fixed issue with map_reduce() and get_result() #157 
it.
(d) I …
> Fixed issue with map_reduce()

- README.md
- docs/configuration.md
- docs/dev-installation.md
> Fixed broken readme links

- README.md
- config/default_config.yaml.template
- docs/dev-installation.md
- pywren_ibm_cloud/compute/compute.py
- pywren_ibm_cloud/wrenconfig.py
> Fixed issue with invocation retries

- pywren_ibm_cloud/storage/storage.py
- Fix storage backend in CLoudObject
it. …
> Fix storage backend in CLoudObject

- pywren_ibm_cloud/compute/compute.py
> Fixed wrong method name: build_runtime()

- README.md
- pywren_ibm_cloud/tests.py
changes:
- integrate argparse module inside the test script.
- add cloudobject test func
- docs update …
> add cloudobject test and improvements

- README.md
- pywren_ibm_cloud/tests.py
**main_changes**:
- change `-f` arg prefix to `-t` for executing a specific test of the test script
- add internal execution test from PyWren inside …
> Add internal execution test

- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/job/job.py
- pywren_ibm_cloud/monitor/wait_rabbitmq.py
- pywren_ibm_cloud/runtime/function_handler/handler.py
- pywren_ibm_cloud/runtime/function_handler/jobrunner.py
Logic for futures returned from a function.
Patch for this #183 
it. …
> Futures returned from a function

- pywren_ibm_cloud/tests.py
> Minor tests.py fix

- examples/knative.py
- pywren_ibm_cloud/compute/backends/knative/__init__.py
- pywren_ibm_cloud/compute/backends/knative/config.py
- pywren_ibm_cloud/compute/backends/knative/knative.py
- pywren_ibm_cloud/runtime/runtime.py
- runtime/knative/Dockerfile
- runtime/knative/app.py
- setup.py
> knative backend impl.

- pywren_ibm_cloud/compute/backends/knative/knative.py
> fix to read namespace from kubeconfig

- docs/data-processing.md
- pywren_ibm_cloud/compute/backends/knative/config.py
- pywren_ibm_cloud/compute/backends/knative/knative.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/runtime/function_handler/handler.py
- pywren_ibm_cloud/runtime/function_handler/jobrunner.py
- pywren_ibm_cloud/storage/storage.py
> Take into account pywren version in knative runtimes

- pywren_ibm_cloud/compute/backends/knative/knative.py
> some fixes for multitenant service

- CHANGELOG.md
- pywren_ibm_cloud/compute/compute.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/job/job.py
- New invoker mechanism that implements a token bucket based scheduling algorithm #209 
Example of 2200 functions:
person who …
> New invoker mechanism

- pywren_ibm_cloud/job/partitioner.py
- pywren_ibm_cloud/tests.py
- added `map()` with different iterdata types tests
- added "return futures" tests
- added `chunk_n` tests …
> add more tests

- pywren_ibm_cloud/tests.py
- improve modularity
- change`result_to_compare` access from COS to an inner class member. …
> Improve tests

- docs/knative.md
> update knative docs

- CHANGELOG.md
- config/config_template.yaml
- docs/api-details.md
- pywren_ibm_cloud/__init__.py
- pywren_ibm_cloud/compute/backends/ibm_cf/config.py
- pywren_ibm_cloud/compute/backends/ibm_cf/entry_point.py
- pywren_ibm_cloud/compute/backends/ibm_cf/ibm_cf.py
- pywren_ibm_cloud/config.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/job/job.py
- pywren_ibm_cloud/runtime/function_handler/__init__.py
- pywren_ibm_cloud/runtime/function_handler/invoker.py
- runtime/ibm_cf/Dockerfile.python37
- runtime/ibm_cf/requirements.txt
- Added new remote invoker
- Fixed issue when using IAM #237 
- Fixed python 3.7 Dockerfile #235 
- Changed default global timeout to None #209 
(c) The contribution was provided directly to me …
> New remote invoker & fixes

- pywren_ibm_cloud/compute/backends/ibm_cf/config.py
- pywren_ibm_cloud/compute/backends/ibm_cf/ibm_cf.py
- pywren_ibm_cloud/compute/backends/openwhisk/config.py
- pywren_ibm_cloud/compute/backends/openwhisk/openwhisk.py
- pywren_ibm_cloud/compute/compute.py
- pywren_ibm_cloud/config.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/libs/openwhisk/client.py
- pywren_ibm_cloud/runtime/function_handler/handler.py
- pywren_ibm_cloud/runtime/function_handler/invoker.py
- pywren_ibm_cloud/runtime/utils.py
- pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py
- pywren_ibm_cloud/storage/utils.py
- Fix timeout value building runtime
- Added IBM COS request retrying when `ibm_botocore.exceptions.ReadTimeoutError` (#247) 
- https://github.com/metaspace2020/pywren-annotation-pipeline/issues/53
in the …
> Fix timeout building runtime

- CHANGELOG.md
- config/README.md
- pywren_ibm_cloud/config.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/job/job.py
- pywren_ibm_cloud/libs/openwhisk/client.py
- pywren_ibm_cloud/runtime/function_handler/handler.py
- pywren_ibm_cloud/runtime/function_handler/invoker.py
- pywren_ibm_cloud/runtime/utils.py
- pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py
- pywren_ibm_cloud/tests.py
- pywren_ibm_cloud/utils.py
- pywren_ibm_cloud/wait/wait_rabbitmq.py
Internal fixes & code refactoring
it. …
> Internal fixes

- pywren_ibm_cloud/compute/backends/ibm_cf/entry_point.py
- pywren_ibm_cloud/compute/backends/knative/entry_point.py
- pywren_ibm_cloud/compute/backends/openwhisk/entry_point.py
- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/runtime/function_handler/handler.py
- pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py
- pywren_ibm_cloud/storage/storage.py
- pywren_ibm_cloud/storage/utils.py
- pywren_ibm_cloud/wait/wait_storage.py
- Added max request attempts when creating a COS client. Default set to 5
- Fixed exception handling in future class
- Added logic to detect running activations
(c) The contribution was …
> Added max req. attempts in COS client

- pywren_ibm_cloud/compute/backends/ibm_cf/entry_point.py
- pywren_ibm_cloud/storage/storage.py
- pywren_ibm_cloud/wait/wait_rabbitmq.py
- pywren_ibm_cloud/wait/wait_storage.py
- prevent get_result wait forever with COS #246 
it. …
> prevent get_result wait forever with COS

- CHANGELOG.md
- pywren_ibm_cloud/config.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/job/job.py
- pywren_ibm_cloud/runtime/function_handler/handler.py
- pywren_ibm_cloud/runtime/function_handler/invoker.py
- pywren_ibm_cloud/runtime/function_handler/jobrunner.py
- pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py
- pywren_ibm_cloud/wait/wait_storage.py
- Reduced the number of COS clients created from each function activation
- Fixed internal issue with storage …
> Internal storage fixes

- CHANGELOG.md
- docs/knative.md
- pywren_ibm_cloud/compute/backends/knative/config.py
- pywren_ibm_cloud/compute/backends/knative/knative.py
IBM CLoud Kubernetes service has updated the versions of the Istio, knative and tekton add-ons.
This patch aligns PyWren to work with these new versions. …
> Updated knative backend

- CHANGELOG.md
- config/README.md
- config/config_template.yaml
- docs/api-details.md
- docs/knative.md
- pywren_ibm_cloud/compute/backends/ibm_cf/config.py
- pywren_ibm_cloud/compute/backends/ibm_cf/ibm_cf.py
- pywren_ibm_cloud/compute/backends/knative/config.py
- pywren_ibm_cloud/compute/backends/knative/knative.py
- pywren_ibm_cloud/compute/backends/knative/tekton/Dockerfile.python36
- pywren_ibm_cloud/compute/backends/knative/tekton/Dockerfile.python37
- pywren_ibm_cloud/compute/backends/knative/tekton/Dockerfile.python38
- pywren_ibm_cloud/compute/backends/localhost/localhost.py
- pywren_ibm_cloud/compute/backends/openwhisk/config.py
- pywren_ibm_cloud/compute/backends/openwhisk/openwhisk.py
- pywren_ibm_cloud/config.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/function/handler.py
- pywren_ibm_cloud/function/utils.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/job/job.py
- pywren_ibm_cloud/libs/openwhisk/client.py
- pywren_ibm_cloud/wait/wait_rabbitmq.py
- runtime/knative/Dockerfile.python36
- runtime/knative/Dockerfile.python37
- runtime/knative/Dockerfile.python38
- Added data_limit config param according to #286 
- Increased internal knative timeout for #287 
- Fixed memory peak measurement
- Allow build default knative runtimes locally. This should help in #283
- Now knative builds the default runtime based on the current python version
- OOM errors are now correctly raised from knative
work with modifications, whether created in whole or in …
>  Added data_limit config param

- pywren_ibm_cloud/compute/backends/knative/knative.py
- pywren_ibm_cloud/function/jobrunner.py
- pywren_ibm_cloud/storage/storage.py
- Fixed knative to pass al tests #287 
- Changed behavior of cloudobjects #289 
person who certified (a), (b) or (c) and I have …
> Fixed knative and cloudobject

- CHANGELOG.md
- README.md
- config/README.md
- docs/api-details.md
- pywren_ibm_cloud/cli/utils.py
- pywren_ibm_cloud/compute/backends/docker/config.py
- pywren_ibm_cloud/compute/backends/docker/docker.py
- pywren_ibm_cloud/compute/backends/docker/entry_point.py
- pywren_ibm_cloud/compute/backends/localhost/config.py
- pywren_ibm_cloud/compute/backends/localhost/localhost.py
- pywren_ibm_cloud/config.py
- pywren_ibm_cloud/function/handler.py
- pywren_ibm_cloud/function/invoker.py
- pywren_ibm_cloud/function/jobrunner.py
- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/job/job.py
- pywren_ibm_cloud/plots.py
- pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py
- pywren_ibm_cloud/storage/backends/infinispan/infinispan.py
- pywren_ibm_cloud/storage/backends/localhost/config.py
- pywren_ibm_cloud/storage/backends/localhost/localhost.py
- pywren_ibm_cloud/storage/backends/swift/swift.py
- pywren_ibm_cloud/storage/storage.py
- pywren_ibm_cloud/storage/utils.py
- pywren_ibm_cloud/tests.py
- Added preliminar version of docker_executor() working in localhost
- Fixed #303 
- Fixed #305 
- Added fix for #300 
- Added fix for #304 
(c) The contribution was provided directly to me by …
> Added preliminar version of docker_executor()

- CHANGELOG.md
- examples/internal_execution.py
- pywren_ibm_cloud/compute/backends/docker/config.py
- pywren_ibm_cloud/compute/backends/docker/docker.py
- pywren_ibm_cloud/compute/backends/docker/entry_point.py
- pywren_ibm_cloud/compute/backends/knative/config.py
- pywren_ibm_cloud/compute/backends/localhost/config.py
- pywren_ibm_cloud/compute/backends/localhost/localhost.py
- pywren_ibm_cloud/compute/backends/openwhisk/config.py
- pywren_ibm_cloud/compute/compute.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/storage/backends/localhost/localhost.py
Modified docker cb to use the docker python sdk (#307 )
it.
(d) I …
> Modified docker cb to use the docker python sdk 

- pywren_ibm_cloud/cli/utils.py
- pywren_ibm_cloud/compute/backends/docker/config.py
- pywren_ibm_cloud/compute/backends/docker/docker.py
- pywren_ibm_cloud/compute/backends/docker/entry_point.py
- pywren_ibm_cloud/compute/backends/localhost/config.py
- pywren_ibm_cloud/compute/backends/localhost/localhost.py
- pywren_ibm_cloud/config.py
- pywren_ibm_cloud/function/handler.py
- pywren_ibm_cloud/function/jobrunner.py
- pywren_ibm_cloud/storage/backends/localhost/config.py
- pywren_ibm_cloud/storage/backends/localhost/localhost.py
- setup.py
- Centralized TMP folder definition in config.py
- Fixed #310 Updated setup.py …
> Updated temp folder definition

- CHANGELOG.md
- docs/functions.md
- examples/multiple_args_map.py
- pywren_ibm_cloud/utils.py
- Fixed issue in extra_args when iterdata is a dict
it.
(d) I …
> Fixed issue in extra_args when iterdata is a dict

- docs/coligo.md
> docs updated

- pywren_ibm_cloud/storage/backends/gcsfs/__init__.py
- pywren_ibm_cloud/storage/backends/gcsfs/config.py
- pywren_ibm_cloud/storage/backends/gcsfs/gcsfs.py
- setup.py
As a part of work I've been doing to get [Dask running on Pywren](https://github.com/tomwhite/dask-executor-scheduler) I've written storage and compute backends for Google Cloud Storage and Cloud Run. This is the PR for the storage backend, which I'd like to contribute to this project.
by me, under the same open source …
> Add support for Google Cloud Storage

- pywren_ibm_cloud/storage/storage.py
> fix CloudObjects keys collisions

- CHANGELOG.md
- README.md
- pywren_ibm_cloud/cli/cli.py
- pywren_ibm_cloud/cli/runtime/cli.py
- pywren_ibm_cloud/cli/utils.py
- pywren_ibm_cloud/compute/backends/docker/docker.py
- pywren_ibm_cloud/compute/backends/ibm_cf/ibm_cf.py
- pywren_ibm_cloud/compute/backends/knative/knative.py
- pywren_ibm_cloud/compute/backends/localhost/localhost.py
- pywren_ibm_cloud/compute/backends/openwhisk/openwhisk.py
- pywren_ibm_cloud/config.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/function/jobrunner.py
- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/invoker.py
- pywren_ibm_cloud/job/job.py
- pywren_ibm_cloud/job/partitioner.py
- pywren_ibm_cloud/libs/openwhisk/client.py
- pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py
- pywren_ibm_cloud/storage/storage.py
- pywren_ibm_cloud/storage/utils.py
- pywren_ibm_cloud/tests.py
Improved Storage abstraction for #320 
Fixed logging #332 
Fixed invoker #324  …
> Improved Storage abstraction & logging fix

- pywren_ibm_cloud/__init__.py
- pywren_ibm_cloud/compute/backends/cloudrun/__init__.py
- pywren_ibm_cloud/compute/backends/cloudrun/cloudrun.py
- pywren_ibm_cloud/compute/backends/cloudrun/config.py
- pywren_ibm_cloud/compute/backends/cloudrun/entry_point.py
- runtime/cloudrun/Dockerfile.conda37
- runtime/cloudrun/Dockerfile.python37
This is the Cloud Run backend I've been using with Dask code in https://github.com/tomwhite/dask-executor-scheduler.
I've also successfully run the following tests:
```
python -m pywren_ibm_cloud.tests -t test_call_async
python -m pywren_ibm_cloud.tests -t test_map
python -m pywren_ibm_cloud.tests -t test_map_reduce
python -m pywren_ibm_cloud.tests -t test_multiple_executions
python -m pywren_ibm_cloud.tests -t test_map_reduce_url
```
---- …
> Add Cloud Run backend

- CHANGELOG.md
- pywren_ibm_cloud/compute/backends/docker/docker.py
- pywren_ibm_cloud/compute/backends/ibm_cf/ibm_cf.py
- pywren_ibm_cloud/compute/backends/knative/knative.py
- pywren_ibm_cloud/compute/backends/localhost/localhost.py
- pywren_ibm_cloud/compute/backends/openwhisk/openwhisk.py
- pywren_ibm_cloud/compute/compute.py
- pywren_ibm_cloud/executor.py
- pywren_ibm_cloud/function/handler.py
- pywren_ibm_cloud/future.py
- pywren_ibm_cloud/invoker.py
> Minor invoker fix

- docs/ibm_vpc.md
- pywren_ibm_cloud/compute/backends/docker/config.py
- pywren_ibm_cloud/compute/backends/docker/docker.py
- pywren_ibm_cloud/libs/docker/clients.py
- pywren_ibm_cloud/libs/docker/clients/ibm_vpc/__init__.py
- pywren_ibm_cloud/libs/docker/clients/ibm_vpc/config.py
- pywren_ibm_cloud/libs/docker/clients/ibm_vpc/ibm_vpc.py
- pywren_ibm_cloud/libs/ibm_utils.py
add IBM VPC service instance client for start/stop interface using the docker executor.
its authentication needs to use IAM api key
example config usage:
```
pywren:
storage_bucket: ***
ibm:
iam_api_key: ***
docker:
host: ***
ssh_user: ***
ssh_password: ***
ssh_key_filename: < path > (OPTIONAL)
remote_client: ibm_vpc
ibm_vpc:
endpoint: ***
instance_id: ***
version: dd-mm-yyyy (OPTIONAL)
generation: 1/2 (OPTIONAL)
ibm_cos:
endpoint: ***
access_key: ***
secret_key: ***
```
example code:
```python
import pywren_ibm_cloud as pywren
def my_func(args):
return 'Hello World'
pw = pywren.docker_executor(storage_backend='ibm_cos')
pw.call_async(my_func, '')
print(pw.get_result())
```
this code will start a VM instance provided by IBM VPC service and will invoke the hello world function into it. …
> add IBM VPC service instance client

- lithops/compute/backends/aws_lambda/__init__.py
- lithops/compute/backends/aws_lambda/aws_lambda.py
- lithops/compute/backends/aws_lambda/config.py
- lithops/compute/backends/aws_lambda/entry_point.py
- lithops/storage/backends/aws_s3/__init__.py
- lithops/storage/backends/aws_s3/aws_s3.py
- lithops/storage/backends/aws_s3/config.py
- Added AWS Lambda and S3 backends
it. …
> AWS Lambda and S3 backends

- lithops/storage/backends/redis/__init__.py
- lithops/storage/backends/redis/config.py
- lithops/storage/backends/redis/redis.py
> add Redis as storage backend

- config/README.md
- config/compute/aliyun_fc.md
- config/compute/aws_lambda.md
- config/compute/azure_fa.md
- config/compute/gcp_functions.md
> add other clouds docs

- CHANGELOG.md
- README.md
- config/README.md
- config/storage/aliyun_oss.md
- config/storage/aws_s3.md
- config/storage/azure_blob.md
- config/storage/gcp_storage.md
- docs/how-to-contribute.md
- lithops/compute/backends/aliyun_fc/requirements.txt
- lithops/compute/backends/azure_fa/action/requirements.txt
Add storage docs
Fix pillow version
it. …
> Add storage docs

- config/compute/code_engine.md
- config/config_template.yaml
- lithops/executors.py
- lithops/invokers.py
- lithops/serverless/backends/code_engine/config.py
Updated config_template.yaml #383 
Updated docs
[ce] Set `remote_invoker=True` in code_engine config file, this way users don't need to set it manually in config file
(c) The contribution was …
> config updated

- examples/map_cos_prefix.py
- examples/map_reduce_cos_bucket.py
- examples/map_reduce_cos_key.py
- lithops/libs/ibm_iam/__init__.py
- lithops/libs/ibm_iam/ibm_iam.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/storage/backends/ibm_cos/ibm_cos.py
IBM IAM logic is abstracted as a library, this way the IBM backends does not need to have duplicated logi …
> abstract ibm_iam logic

- config/README.md
- config/config_template.yaml
- lithops/config.py
- lithops/invokers.py
- lithops/job/job.py
- lithops/job/partitioner.py
- lithops/standalone/standalone.py
- lithops/wait/wait_storage.py
- lithops/worker/handler.py
- runtime/ibm_cf/Dockerfile.slim
Fixed issue found in partitioner
Added execution_timeout parameter in config …
> fix in partitioner

- lithops/libs/ibm_iam/ibm_iam.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/storage/backends/ibm_cos/ibm_cos.py
> fix in IAM/COS tokens

- lithops/localhost/localhost.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/proxy.py
- lithops/standalone/standalone.py
> Fix for lithops waiting forever

- lithops/invokers.py
- lithops/serverless/backends/knative/knative.py
tentative fix in knative for #406 
it. …
> Fix in knative

- lithops/invokers.py
> fix to #404

- lithops/multiprocessing/__init__.py
- lithops/multiprocessing/cloud_proxy.py
- lithops/multiprocessing/connection.py
- lithops/multiprocessing/context.py
- lithops/multiprocessing/managers.py
- lithops/multiprocessing/pool.py
- lithops/multiprocessing/popen_cloud.py
- lithops/multiprocessing/process.py
- lithops/multiprocessing/queues.py
- lithops/multiprocessing/reduction.py
- lithops/multiprocessing/synchronize.py
- lithops/multiprocessing/util.py
Add multiprocessing API
It does not contain any modification in the lithops core
person who certified (a), (b) or (c) and I have …
> Add multiprocessing API

- CHANGELOG.md
- lithops/config.py
- lithops/localhost/local_handler.py
- lithops/localhost/localhost.py
- lithops/serverless/backends/knative/knative.py
- lithops/standalone/proxy.py
- lithops/version.py
- lithops/worker/handler.py
Move master branch version name to dev
Minor fixes in localhost executor …
> Minor fixes in localhost

- lithops/cli/cli.py
- lithops/cli/runtime/cli.py
- lithops/cli/utils.py
- lithops/config.py
- lithops/executors.py
- lithops/invokers.py
- lithops/localhost/local_handler.py
- lithops/localhost/localhost.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/azure_fa/azure_fa.py
- lithops/serverless/backends/cloudrun/cloudrun.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- lithops/serverless/serverless.py
- lithops/standalone/standalone.py
- lithops/tests.py
- renamed `delete_all_runtimes()` to `clean()`
- Add --executor option in `lithops verify` cli …
> Minor modifications in lithops cli

- CHANGELOG.md
- lithops/cli/utils.py
- lithops/config.py
- lithops/invokers.py
- lithops/localhost/local_handler.py
- lithops/localhost/localhost.py
- lithops/serverless/backends/aws_lambda/entry_point.py
- lithops/serverless/backends/cloudrun/entry_point.py
- lithops/serverless/backends/code_engine/entry_point.py
- lithops/serverless/backends/ibm_cf/entry_point.py
- lithops/serverless/backends/knative/entry_point.py
- lithops/serverless/backends/openwhisk/entry_point.py
- lithops/standalone/proxy.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/worker/handler.py
- lithops/worker/invoker.py
- lithops/worker/jobrunner.py
- Improved logging in localhost/standalone
Previous logs were almost impossible to debug:
```
[INFO] handler: Execution-ID: 896532/0/M000/00001
[INFO] handler: Execution-ID: 896532/0/M000/00000
[INFO] handler: Execution-ID: 896532/0/M000/00002
[INFO] handler: Execution-ID: 896532/0/M000/00003
[INFO] JobRunner: Started
[INFO] JobRunner: Started
[INFO] JobRunner: Started
[INFO] JobRunner: Started
[INFO] JobRunner: Going to execute 'lithops_inside_lithops_map_function()'
[INFO] JobRunner: Going to execute 'lithops_inside_lithops_map_function()'
---------------------- FUNCTION LOG ----------------------
---------------------- FUNCTION LOG ----------------------
[INFO] lithops.config: Lithops v2.2.dev3
[INFO] lithops.config: Lithops v2.2.dev3
[INFO] lithops.config: Lithops v2.2.dev3
[INFO] …
```
> Improved logging in localhost/standalone

- lithops/standalone/proxy.py
Currently its time calculation is wrong.
It is taking into account time spent for execution …
> Fixing soft dismantle timeout

- config/README.md
- config/compute/ibm_vpc.md
- config/compute/localhost.md
- config/compute/remote_vm.md
- config/config_template.yaml
- docs/api-details.md
- lithops/__init__.py
- lithops/cli/cli.py
- lithops/cli/utils.py
- lithops/config.py
- lithops/executors.py
- lithops/future.py
- lithops/invokers.py
- lithops/job/job.py
- lithops/localhost/localhost.py
- lithops/localhost/runner.py
- lithops/multiprocessing/cloud_proxy.py
- lithops/plots.py
- lithops/standalone/standalone.py
- lithops/storage/backends/ibm_cos/config.py
- lithops/tests.py
- lithops/version.py
- This patch synchronize the VM function logs with a local file when using standalone mode of execution #338 
- Allow allow to run lithops without a config file in localhost execution mode #424 
in the file; …
> Sync remote function logs with local file

- docs/functions.md
- examples/storage_arg.py
- lithops/cli/cli.py
- lithops/cli/logs/cli.py
- lithops/cli/runtime/utils.py
- lithops/cli/utils.py
- lithops/config.py
- lithops/executors.py
- lithops/future.py
- lithops/invokers.py
- lithops/localhost/localhost.py
- lithops/localhost/runner.py
- lithops/standalone/proxy.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/storage/backends/localhost/localhost.py
- lithops/storage/storage.py
- lithops/tests.py
- lithops/utils.py
- lithops/worker/handler.py
- standalone logs per job-id #338 
- minor tentative fix for #304  …
> standalone logs per job-id

- CHANGELOG.md
- config/compute/ibm_vpc.md
- config/compute/localhost.md
- config/compute/vm.md
- lithops/scripts/cli.py
- lithops/standalone/standalone.py
- lithops/storage/backends/localhost/localhost.py
- fix in localhost storage
- fix in lithops logs cli
it.
(d) I …
> Minor fix in localhost storage

- CHANGELOG.md
- lithops/config.py
- lithops/job/partitioner.py
- lithops/localhost/runner.py
- lithops/standalone/standalone.py
- lithops/storage/backends/localhost/localhost.py
- lithops/storage/storage.py
- lithops/storage/utils.py
- lithops/utils.py
- Fixes for windows and localhost mode
- Fix job monitoring on Windows hosts
- delete print …
> Fixes for windows and localhost mode

- config/storage/ibm_cos.md
- lithops/storage/backends/ibm_cos/config.py
- Add region parameter in IBM COS config.
it. …
> Add region in IBM COS config

- lithops/serverless/backends/aws_lambda/aws_lambda.py
- Added info logs when creating custom AWS Lambda runtime
it.
(d) I …
> [Lambda] Added info logs when creating custom runtime

- CHANGELOG.md
- lithops/job/job.py
- lithops/job/partitioner.py
- lithops/utils.py
- runtime/knative/Dockerfile.conda
- runtime/knative/Dockerfile.python36
- runtime/knative/Dockerfile.python37
- runtime/knative/Dockerfile.python38
> Fixed partitioner

- CHANGELOG.md
- examples/storage.py
- lithops/__init__.py
- lithops/config.py
- lithops/localhost/localhost.py
- lithops/scripts/cli.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/serverless.py
- lithops/storage/storage.py
- Allow to create a Storage() class from config file
- Updated changelog
- Add storage API example
person who certified (a), (b) …
> Allow to create a Storage() class from config file

- CHANGELOG.md
- README.md
- docs/api_storage.md
- examples/storage_os.py
- runtime/knative/README.md
> Add storage examples in docs

- CHANGELOG.md
- lithops/localhost/runner.py
- lithops/serverless/backends/code_engine/code_engine.py
> Allow Windows hosts to run functions in processes instead of threads

- docs/api_multiprocessing.md
- examples/multiprocessing/pool.py
- Added multiprocessing API docs
- Updated multiprocessing examples …
> [multiprocessing] Added API docs

- CHANGELOG.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/serverless.py
- lithops/wait/wait_rabbitmq.py
- lithops/wait/wait_storage.py
- setup.py
- Add clear() method in CodeEngine
- Add tblib.pickling_support for the local machine #483  …
> Add clear() method in CodeEngine

- CHANGELOG.md
- docs/mode_localhost.md
- lithops/config.py
- lithops/constants.py
- lithops/libs/openwhisk/client.py
- lithops/localhost/localhost.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/standalone/standalone.py
- lithops/util/ibm_token_manager.py
- Request a new token in IBM CF when it expires during an execution #485 
- Fix in localhost Storage API
- Fix in code engine #489  …
> Fixed expired IAM token in IBM CF during an execution

- lithops/storage/backends/azure_blob/azure_blob.py
> Update Azure Blob Storage backend

- config/storage/azure_blob.md
- lithops/storage/backends/azure_blob/azure_blob.py
> Update Azure Blob Storage backend & docs

- CHANGELOG.md
- config/compute/azure_fa.md
- lithops/config.py
- lithops/job/partitioner.py
- lithops/serverless/backends/azure_fa/azure_fa.py
- lithops/serverless/backends/azure_fa/config.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/storage/backends/ibm_cos/config.py
- lithops/storage/storage.py
Fixed storage API for localhost
it. …
> Fixed storage API

- lithops/tests.py
Fixes the issue in the `test_storage_handler` test introduced in #495 
* Moves test dataset into a sub-prefix
* Deletes any objects that aren't in the sub-prefix between each test
(c) The …
> Fix test_storage_handler issue

- CHANGELOG.md
- CONTRIBUTING.md
- config/README.md
- docs/dso.md
- docs/user_guide.md
- lithops/executors.py
- lithops/scripts/cli.py
- lithops/scripts/tests.py
- Fixed logging in executor
- Moved DSO docs to user guide
- Moved tests.py script to `scripts` folder to prevent issues with multiprocessing lib
- Add logging to tests script
(c) The …
> Fixed logging in executor

- config/README.md
- config/config_template.yaml
- docs/api_multiprocessing.md
- docs/api_storage.md
- docs/data_processing.md
- docs/mode_serverless.md
- docs/sklearn_joblib.md
- docs/supported_clouds.md
> minor docs update

- config/compute/code_engine.md
- config/compute/knative.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/knative/config.py
- lithops/serverless/backends/knative/knative.py
Allow custom container registry in code engine and knative #505 
it. …
> Allow custom container registry

- config/compute/ibm_vpc.md
- config/config_template.yaml
- config/ibm_vpc/ubuntu-20.04-server-cloudimg-amd64.sh
- lithops/localhost/runner.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/proxy.py
- lithops/standalone/standalone.py
- lithops/util/ssh_client.py
- lithops/utils.py
> Enablement of IBM VPC backend to create VMs dynamically in runtime 

- lithops/standalone/standalone.py
> [standalone] fixing extract metadata

- config/compute/aws_lambda.md
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
- Closes #460
- Closes #461
it. …
> [Lambda] Implemented configuration for VPC and EFS for Lithops function

- lithops/standalone/standalone.py
- lithops/util/ssh_client.py
Reverts lithops-cloud/lithops#523
> Revert "update wait_backend_ready method"

- lithops/util/ssh_client.py
Update wait_backend_ready() method to detect a more accurate time when the VM is ready to receive commands, and avoid possible ssh errors #516 
(c) The contribution was provided directly to me …
> update wait_backend_ready method

- CHANGELOG.md
- lithops/localhost/localhost.py
- lithops/worker/utils.py
Fix for Localhost mode when using a docker image in Windows ad MAC OS …
> Fix localhost mode in macos and windows

- lithops/localhost/localhost.py
> added missing setup argument

- lithops/standalone/standalone.py
> added sleep after service registration

- README.md
- runtime/ibm_cf/Dockerfile.gromacs
- runtime/ibm_cf/README.md
- Add updated gromacs Dockefile
- Add links to papers
it.
(d) I …
> Add updated gromacs Dockefile

- README.md
- lithops/scripts/cli.py
- lithops/scripts/tests.py
- lithops/serverless/backends/ibm_cf/config.py
- Add storage arg in lithops console cli. This allows more flexibility to choose the desired storage backend when running commands with the lithops console cli …
> Add storage arg in lithops console cli

- CHANGELOG.md
- config/README.md
- config/config_template.yaml
- docs/api_futures.md
- examples/joblib_backend.py
- examples/multiprocessing/counter.py
- examples/multiprocessing/pool.py
- examples/sklearn_job.py
- lithops/config.py
- lithops/constants.py
- lithops/executors.py
- lithops/localhost/runner.py
- lithops/scripts/cli.py
- lithops/scripts/tests.py
- lithops/serverless/backends/aliyun_fc/entry_point.py
- lithops/serverless/backends/aws_lambda/entry_point.py
- lithops/serverless/backends/azure_fa/entry_point.py
- lithops/serverless/backends/cloudrun/entry_point.py
- lithops/serverless/backends/code_engine/entry_point.py
- lithops/serverless/backends/gcp_functions/entry_point.py
- lithops/serverless/backends/ibm_cf/entry_point.py
- lithops/serverless/backends/knative/entry_point.py
- lithops/serverless/backends/openwhisk/entry_point.py
- lithops/utils.py
Allow to configure lithops logging from config file
- add 'log_level' and 'log_format' keys in config
- add 'log_stream' and 'log_filename' keys in config …
> add log_level and log_format in config

- config/README.md
- config/config_template.yaml
- lithops/localhost/localhost.py
- lithops/localhost/runner.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/proxy.py
- lithops/standalone/standalone.py
> [standalone][ibm_vpc] avoid docker pull or load if runtime installed in the custom VM image

- lithops/serverless/backends/azure_fa/azure_fa.py
> Implement missing azure_fa backend methods

- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/knative/config.py
- lithops/utils.py
- runtime/ibm_vpc/build_lithops_vm_image.sh
- Fix getting docker username in MAC OS hosts
- Add '-p prune' param in vpc build script
person who certified (a), (b) or (c) and …
> Fix getting docker username in MAC OS hosts

- config/compute/ibm_vpc.md
- lithops/standalone/standalone.py
> [vpc] minor fixes

- lithops/scripts/cli.py
This patch allows to operate the storage backend using the `lithops` console cli.
Currently it supports `put`, `get`, `delete` and `list` operations, for example:
```bash
$ lithops storage put test.txt my-bucket
$ lithops storage get my-bucket test.txt
$ lithops storage list my-bucket
$ lithops storage delete my-bucket test.txt
```
work with modifications, whether created in whole or …
> extend lithops cli with storage option

- runtime/ibm_vpc/build_lithops_vm_image.sh
> fix vpc build script

- lithops/constants.py
- lithops/standalone/master.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
> fix standalone log file

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/standalone.py
> force close ssh connection

- lithops/executors.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
Useful when there are tens of worker VMs
it. …
> [IBM VPC] clear VMs using threads

- README.md
- lithops/standalone/standalone.py
Minor change to reduce logic and make it better understandable
it. …
> [standalone] minor refactor in standalone run method

- lithops/standalone/master.py
> [standalone] add log

- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/worker.py
> Standalone improvements

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/master.py
> fix checking if a vm is already created

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/master.py
> [standalone] recreate worker vms after a timeout

- lithops/localhost/localhost.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/worker.py
> [Standalone] Add work queue

- lithops/job/job.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
Fixed #575 
Minor fix in IBM VPC backend
it. …
> minor fixes

- lithops/standalone/master.py
- lithops/util/ssh_client.py
> fix for ssh key filename

- lithops/standalone/master.py
- lithops/standalone/standalone.py
> add more logs on master vm service

- lithops/standalone/keeper.py
- lithops/standalone/master.py
> [standalone] minor fix in master logging

- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/k8s/k8s.py
Delete resources only from current executor when clean() method is called …
> clear current executor jobs

- lithops/multiprocessing/pool.py
Encapsulating Pool map params to work with lithops futures api.
it. …
> Encapsulate pool map params

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/scripts/tests.py
- lithops/serverless/backends/knative/knative.py
fix --config option on cli #585 
it. …
> fix --config option on cli

- CHANGELOG.md
- lithops/standalone/standalone.py
Fixed internal executions in standalone mode to pass all tests
it. …
> fixed internal executions in standalone

- lithops/serverless/backends/knative/config.py
- runtime/knative/Dockerfile
- setup.py
> include storage libs into default knative runtime

- lithops/executors.py
- lithops/wait/wait_rabbitmq.py
> fix rabbitmq get_result() after wait()

- CHANGELOG.md
- config/compute/k8s_job.md
- config/storage/azure_blob.md
- lithops/future.py
- lithops/serverless/backends/azure_fa/azure_fa.py
- lithops/storage/backends/azure_blob/azure_blob.py
- lithops/version.py
> [Azure] fix for azure blob storage

- config/compute/code_engine.md
- lithops/scripts/tests.py
- lithops/serverless/backends/azure_fa/azure_fa.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/worker/handler.py
- lithops/worker/utils.py
> Enable internal executions in code engine and k8s backends

- CHANGELOG.md
- lithops/config.py
- lithops/utils.py
> overwrite runtime set in config with the one set in FunctionExecutor

- lithops/utils.py
> minor fix in log

- lithops/config.py
- lithops/serverless/backends/k8s/k8s.py
log config file location in debug logs
it. …
> log config file location

- CHANGELOG.md
- lithops/config.py
- lithops/scripts/cli.py
- lithops/serverless/backends/azure_fa/azure_fa.py
add empty method to lithops storage cli. This method allows to empty a bucket using the lithops cli
person who certified (a), (b) …
> add empty method to lithops storage cli

- lithops/executors.py
- lithops/serverless/backends/ibm_cf/config.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
> move pandas import within costs method

- examples/map_cos_prefix.py
- examples/map_reduce.py
- examples/map_reduce_cos_bucket.py
- examples/map_reduce_cos_key.py
- examples/map_reduce_url.py
- lithops/job/partitioner.py
Fix partitioner examples and update partitioner logging
it.
(d) I …
> fix examples and update partitioner logging

- lithops/localhost/runner.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
change mp start method for MacOS
fix in k8s backend
it.
(d) I …
> change mp start method for MacOS

- examples/cloudobject.py
- examples/ibmcos_arg.py
- examples/rabbitmq_arg.py
- examples/storage.py
- examples/storage_arg.py
> fix examples

- CHANGELOG.md
- config/compute/azure_functions.md
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/azure_functions/config.py
- lithops/serverless/backends/azure_functions/entry_point.py
- lithops/storage/backends/azure_blob/azure_blob.py
- lithops/worker/handler.py
> [Azure Functions] Enable http trigger

- lithops/invokers.py
- lithops/localhost/runner.py
> fix extract runtime preinstalls in localhost

- lithops/localhost/localhost.py
> Move some localhost logs to debug

- CHANGELOG.md
- config/compute/code_engine.md
- lithops/config.py
> Set lithops to localhost mode when config files is empty

- lithops/serverless/backends/code_engine/code_engine.py
> Allow 'dots' in code-engine runtime name

- CHANGELOG.md
- lithops/future.py
- lithops/plots.py
- lithops/worker/handler.py
- lithops/worker/taskrunner.py
> Add "warm_container" and "func_result_size" to call stats

- lithops/monitor.py
This will show pending, running and done invocations over time
it. …
> add more descriptive debug message in monitor

- lithops/invokers.py
- lithops/worker/taskrunner.py
> Fix in prometheus telemetry

- runtime/README.md
- runtime/kubernetes/Dockerfile
- runtime/kubernetes/Dockerfile.conda
- runtime/kubernetes/README.md
> Add instructions for building k8s runtimes

- lithops/future.py
- lithops/monitor.py
- lithops/serverless/backends/k8s/entry_point.py
- lithops/wait.py
Minor fix in monitor to make it slightly faster, keeping the current low level of number of requests
person who certified (a), (b) …
> Minor fix in monitor

- lithops/executors.py
- lithops/future.py
- lithops/monitor.py
- lithops/wait.py
> fixes for rabbitmq monitoring

- CHANGELOG.md
- lithops/future.py
- lithops/monitor.py
- lithops/scripts/tests.py
- lithops/version.py
> Fix for internal executions

- examples/internal_execution.py
- lithops/future.py
- lithops/invokers.py
- lithops/job/serialize.py
- lithops/monitor.py
- lithops/wait.py
- lithops/worker/handler.py
- lithops/worker/status.py
Now rabbitmq passes all tests for the first time
it. …
> Make rabbitmq monitor fully working

- lithops/executors.py
- lithops/monitor.py
Fixed `executor.wait()` method to stop only present jobs
Fixed minor issue in` executor.job_summary()` method …
> fixes in executor

- lithops/invokers.py
- lithops/job/serialize.py
- lithops/version.py
- lithops/worker/invoker.py
> Serverless remote invoker working according with new monitoring system

- lithops/job/serialize.py
> Fix for bound methods

- CHANGELOG.md
- config/README.md
- lithops/job/job.py
- lithops/worker/jobrunner.py
- docs update
- Allow to execute a Class as lithops function
it.
(d) …
> Docs update & fix for function executor

- config/compute/code_engine.md
- config/compute/knative.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/knative/config.py
Memory and CPU values must match combinations from https://cloud.ibm.com/docs/codeengine?topic=codeengine-mem-cpu-combo
person who …
> set code engine to correct cpu and memory values

- CHANGELOG.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
> Allow to use IBM IAM API key in Code Engine

- CHANGELOG.md
- lithops/executors.py
- lithops/localhost/localhost.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/serverless.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/standalone.py
- lithops/util/ibm_token_manager.py
- lithops/wait.py
Clear only present jobs instead of all to prevent lithops waiting forever …
> clear only present jobs

- CHANGELOG.md
- config/compute/code_engine.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
> allow to run code engine without kubecfg file

- config/compute/k8s_job.md
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
> update k8s backend config parameters

- lithops/localhost/localhost.py
> Fix for paths in windows hosts

- lithops/invokers.py
- lithops/version.py
- lithops/worker/jobrunner.py
> fix prometheus metrics

- docs/functions.md
> fix broken link

- CHANGELOG.md
- docs/data_processing.md
- docs/functions.md
- examples/map_reduce_localhost.py
- examples/map_reduce_path.py
- lithops/config.py
- lithops/invokers.py
- lithops/job/partitioner.py
- lithops/localhost/localhost.py
- lithops/localhost/runner.py
- lithops/scripts/tests.py
- lithops/serverless/serverless.py
- lithops/standalone/standalone.py
- lithops/storage/utils.py
- lithops/utils.py
- lithops/worker/jobrunner.py
- lithops/worker/utils.py
allow the partitioner to process local files in locahost mode
it.
(d) …
> allow the partitioner to process local files in locahost mode

- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
Fix container registry in k8s backend
it. …
> Fix k8s backend

- lithops/serverless/serverless.py
> minor fix in invoker

- lithops/job/serialize.py
> minor fix in lithops module analyzer

- CHANGELOG.md
- config/README.md
- config/compute/ibm_cf.md
- docs/functions.md
- docs/user_guide.md
> Fix broken links

- lithops/worker/jobrunner.py
> add key and bucket to localhost file

- CHANGELOG.md
- lithops/version.py
> update version and changelog

- lithops/invokers.py
Co-authored-by: Enrique Martinez <enrique.martinez@estudiants.urv.cat>
Co-authored-by: Jordi Bayarri <jordi.bayarri@estudiants.urv.cat> …
> Fix function invocation when there are no free workers available

- lithops/executors.py
- setup.py
> clear compute backend only when data_cleaner=True

- CHANGELOG.md
- config/compute/ibm_vpc.md
- docs/functions.md
- lithops/utils.py
> make obj.data_stream an iterator

- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aliyun_fc/config.py
- lithops/serverless/backends/aws_lambda/config.py
- lithops/serverless/backends/azure_functions/config.py
- lithops/serverless/backends/gcp_cloudrun/config.py
- lithops/serverless/backends/gcp_functions/config.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/knative/config.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/config.py
Some config update for those non-IBM backends
it. …
> update non-IBM backends

- lithops/config.py
- lithops/serverless/backends/aliyun_fc/config.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/standalone/backends/ibm_vpc/config.py
Minor fix in Kubernetes backend
it. …
> Update k8s backend

- lithops/scripts/cli.py
> fix client

- CHANGELOG.md
- config/README.md
- config/compute/aliyun_fc.md
- config/compute/aws_lambda.md
- config/compute/azure_functions.md
- config/compute/gcp_cloudrun.md
- config/compute/gcp_functions.md
- config/compute/knative.md
- config/compute/openwhisk.md
- config/compute/vm.md
> docs update

- CHANGELOG.md
- lithops/invokers.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/entry_point.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/serverless.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/standalone.py
allow to set max workers in k8s backend
it. …
> [k8s] allow to set max workers in k8s backend

- lithops/config.py
- lithops/serverless/backends/k8s/k8s.py
> minor fix in config

- lithops/localhost/localhost.py
> fix in localhost

- config/README.md
- config/storage/ibm_cos.md
- lithops/config.py
- lithops/storage/backends/ibm_cos/config.py
> fix in storage config

- CHANGELOG.md
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
- runtime/aws_lambda/README.md
- runtime/aws_lambda/requirements.txt
- Deleted custom layer runtimes for AWS Lambda backend
- Updated list of available modules for the default lambda runtime (#694) …
> Lambda patch

- docs/data_processing.md
- lithops/executors.py
- lithops/job/partitioner.py
Allow localhost directories as an input data of the partitioner in the localhost mode
person who certified (a), (b) or (c) and I …
> Allow localhost directories as an input data of the partitioner

- CHANGELOG.md
- lithops/config.py
- lithops/job/partitioner.py
- lithops/storage/utils.py
- lithops/worker/jobrunner.py
> fixed exception when processing localhost files

- lithops/job/serialize.py
> Fix in serializer

- lithops/job/serialize.py
Minor change in serializer for preventing duplicated method execution when inspecting the modules …
> Minor change in serializer

- CHANGELOG.md
- docs/api_storage.md
- lithops/config.py
> Allow to create a localhost storage instance when a config file exists

- CHANGELOG.md
- config/README.md
- config/config_template.yaml
- lithops/config.py
- lithops/constants.py
- lithops/future.py
- lithops/invokers.py
- lithops/job/job.py
- lithops/storage/utils.py
- lithops/worker/utils.py
Fix in config to propagate serverless config keys
Fix customized runtime feature
Fix get_result() execution after wait() when throw_except is False
(c) The contribution was provided directly to …
> Fix customized runtime feature

- CHANGELOG.md
- config/README.md
- config/config_template.yaml
- config/storage/ceph.md
- config/storage/minio.md
- docs/supported_clouds.md
- lithops/job/job.py
- lithops/storage/backends/aws_s3/aws_s3.py
- lithops/storage/backends/aws_s3/config.py
- lithops/storage/backends/ceph/config.py
- lithops/storage/backends/minio/__init__.py
- lithops/storage/backends/minio/config.py
- lithops/storage/backends/minio/minio.py
> Add MinIO Storage backend

- lithops/executors.py
- lithops/job/job.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/knative/knative.py
> Allow to dump byte strs

- config/storage/ceph.md
- config/storage/minio.md
- examples/function_chaining.py
- lithops/storage/backends/aws_s3/config.py
- lithops/storage/backends/ceph/ceph.py
- lithops/storage/backends/ceph/config.py
- lithops/storage/backends/minio/config.py
- lithops/storage/backends/minio/minio.py
- lithops/utils.py
- lithops/worker/jobrunner.py
Fix function chaining feature
it. …
> Fix function chaining

- CHANGELOG.md
- config/compute/aws_lambda.md
- docs/api_futures.md
- lithops/executors.py
- lithops/invokers.py
- lithops/job/job.py
- lithops/scripts/cli.py
- lithops/storage/storage.py
- lithops/storage/utils.py
- lithops/utils.py
- lithops/worker/jobrunner.py
- lithops/worker/status.py
Optimize call_async invocation with an internal function cache
This substantially improves the performance of call async jobs when multiple call asyncs are executed in a row with the same function
in the file; …
> Optimize call_async invocation with an internal function cache

- lithops/executors.py
- lithops/monitor.py
- lithops/worker/handler.py
- lithops/worker/jobrunner.py
- lithops/worker/status.py
> fix rabbitmq monitor

- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
This can potentially reduce function invocation time in AWS Lambda:
To activate the feature add in config:
```yaml
aws_lambda:
beta_features: true
```
Invocation example with current_master branch:
Invocation Example with this patch:
permitted to submit under a …
> new beta invocation method for aws_lambda

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/worker/invoker.py
> minor fix in aws lambda and remote_invoke

- CHANGELOG.md
- config/storage/aliyun_oss.md
- config/storage/azure_blob.md
- config/storage/ceph.md
- config/storage/minio.md
- lithops/executors.py
- lithops/localhost/localhost.py
- lithops/localhost/runner.py
- lithops/scripts/cleaner.py
With this patch, when using Localhost mode, jobs background processes are killed when a user press ctrl-c or an exception is produced. …
> [localhost] stop running jobs processes on ctrl-c or exception

- CHANGELOG.md
- config/config_template.yaml
- config/storage/aliyun_oss.md
- config/storage/aws_s3.md
- config/storage/azure_blob.md
- config/storage/ceph.md
- config/storage/gcp_storage.md
- config/storage/ibm_cos.md
- config/storage/minio.md
- config/storage/swift.md
- examples/hello_world.ipynb
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
- lithops/storage/backends/aws_s3/aws_s3.py
- lithops/storage/backends/aws_s3/config.py
- setup.py
> allow to set region_name in s3

- config/compute/aws_lambda.md
- config/storage/aws_s3.md
- config/storage/ibm_cos.md
- config/storage/redis.md
- lithops/executors.py
- lithops/invokers.py
- lithops/storage/backends/redis/redis.py
- lithops/util/metrics.py
- lithops/worker/jobrunner.py
Update prometheus metrics to include metric type
it. …
> Prometheus metrics update

- config/README.md
- lithops/executors.py
- lithops/job/serialize.py
- lithops/scripts/cli.py
> Fix in cli and serializer

- CHANGELOG.md
- config/README.md
- config/compute/aliyun_fc.md
- config/compute/aws_lambda.md
- config/compute/azure_batch.md
- config/compute/azure_functions.md
- config/compute/code_engine.md
- config/compute/gcp_cloudrun.md
- config/compute/gcp_functions.md
- config/compute/ibm_cf.md
- config/compute/ibm_vpc.md
- config/compute/k8s_job.md
- config/compute/knative.md
- config/compute/openwhisk.md
- config/compute/vm.md
- config/config_template.yaml
- docs/mode_localhost.md
- docs/mode_serverless.md
- docs/mode_standalone.md
- lithops/executors.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
> Add missing configuration docs

- config/README.md
- docs/file_chunking.md
- docs/prometheus.md
- docs/supported_clouds.md
- examples/internal_execution.py
- lithops/invokers.py
- lithops/localhost/localhost.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/worker/handler.py
- lithops/worker/jobrunner.py
> update prom metrics and docs

- CHANGELOG.md
- config/compute/ibm_vpc.md
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
> fixes in ibm_vpc

- .github/workflows/main.yml
- CONTRIBUTING.md
- DEVELOPMENT.md
- docs/ci_github_workflow.md
- docs/testing.md
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- runtime/code_engine/Dockerfile.githubci
- runtime/code_engine/requirements.txt
Skip tests if config not present
Add missing libs in code engine
minor fix in standalone
person who certified (a), (b) or (c) and …
> Skip tests if config not present

- lithops/serverless/backends/aws_lambda/config.py
> fixed aws config max timeout check

- lithops/serverless/backends/code_engine/code_engine.py
- lithops/util/ibm_token_manager.py
This will prevent a job to fail due token expired
Might fix #751 
it. …
> Refresh CE IAM token on invoke

- CHANGELOG.md
- lithops/serverless/backends/code_engine/code_engine.py
> minor fix in CE config

- CHANGELOG.md
- lithops/config.py
- lithops/constants.py
- lithops/executors.py
- lithops/job/job.py
> Move worker_processes to FunctionExecutor

- config/README.md
- lithops/config.py
- lithops/executors.py
- lithops/localhost/localhost.py
- lithops/localhost/runner.py
- lithops/standalone/master.py
- lithops/standalone/worker.py
- lithops/worker/handler.py
- setup.py
This will prevent OOM and jobs disturbing other jobs #436
it.
(d) I …
> Prevent localhost to run multiple maps at the same time

- CHANGELOG.md
- config/compute/ibm_vpc.md
- config/compute/vm.md
- lithops/localhost/localhost.py
- lithops/localhost/runner.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/config.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/worker.py
> Fixes in standalone

- CHANGELOG.md
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
> Fix issue in standalone that prevents to run multiple maps with 1 fexec

- lithops/localhost/localhost.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/worker.py
- lithops/tests/test_map.py
- lithops/tests/tests_main.py
- lithops/worker/handler.py
Gracefully start and stop localhost job manager
Clean all CE configmaps on `lithops clean`
Revert tests datasates (Current test dataset introduced in #683 produce timeouts, making tests to fail.)
Fixed #702
in …
> Fixes in localhost, tests, and standalone

- lithops/localhost/localhost.py
- lithops/tests/test_map.py
- lithops/worker/handler.py
> fix tests execution on VPC and CE

- lithops/worker/handler.py
- lithops/worker/status.py
> minor fix in worker handler

- README.md
- docs/cli.md
- docs/user_guide.md
- lithops/scripts/cli.py
- lithops/standalone/master.py
- lithops/tests/test_map.py
- lithops/util/ibm_token_manager.py
- lithops/worker/status.py
> Add CLI docs

- lithops/config.py
- runtime/ibm_cf/Dockerfile.slim
- runtime/kubernetes/Dockerfile
- runtime/kubernetes/Dockerfile.conda
> Minor update in dockerfiles

- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/worker.py
> fixes reuse mode

- CHANGELOG.md
- config/README.md
- config/compute/aliyun_functions.md
- config/storage/aliyun_oss.md
- lithops/constants.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aliyun_fc/config.py
- lithops/serverless/backends/aliyun_fc/entry_point.py
- lithops/storage/backends/aliyun_oss/aliyun_oss.py
- lithops/storage/backends/aliyun_oss/config.py
- runtime/ibm_cf/Dockerfile.slim
> Fixes in alibaba function compute

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
> remove private ssh key from workers config

- CHANGELOG.md
- docs/api_futures.md
- examples/map_reduce.py
- lithops/executors.py
- lithops/wait.py
Spawn the reduce function in map_reduce() after a configurable X% of done maps …
> Spawn the reduce function in map_reduce() after a X% of done maps

- lithops/localhost/localhost.py
> [Localhost] Fix localhost paths

- CHANGELOG.md
- lithops/localhost/localhost.py
> Gracefully Kill localhost jobs on ctrl-c

- config/compute/ibm_vpc.md
- config/compute/k8s_job.md
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
> fix runtime timeout in k8s backend

- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/k8s.py
> minor fix in k8s and ibm_cf backend

- CHANGELOG.md
- lithops/config.py
- lithops/executors.py
- lithops/scripts/cli.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/storage/storage.py
- lithops/tests/test_map.py
- lithops/tests/test_template.py
- lithops/wait.py
- runtime/code_engine/Dockerfile
- runtime/code_engine/Dockerfile.conda
- runtime/code_engine/Dockerfile.opencv
Fix in config, tests and map_reduce
delete configmaps and jobruns created in internal_executions …
> Fix in config, tests and map_reduce

- CHANGELOG.md
- docs/source/compute_config/aws_ec2.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/master.py
> Fix aws ec2 init method

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
to avoid it, added validation to check that master ip injected in
master setup script is not None …
> In some edge cases master instance ip is None

- CHANGELOG.md
- docs/source/compute_config/aws_ec2.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/master.py
- lithops/standalone/utils.py
- lithops/storage/backends/aws_s3/aws_s3.py
> Add logic for AWS EC2 Spot instances

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/utils.py
> Added except/retry logic to vpc client

- CHANGELOG.md
- docs/source/compute_config/aws_ec2.md
- lithops/localhost/localhost.py
- lithops/scripts/cli.py
- lithops/serverless/serverless.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/worker.py
> [AWS_EC2] set spot instances as default in aws ec2 backend

- config/config_template.yaml
- docs/source/compute_config/aws_ec2.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/master.py
> update aws ec2 worker instance type

- CHANGELOG.md
- docs/source/cli.rst
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/ibm_vpc.md
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
- Allow to login worker VMs from master through pub key
- Add new command "lithops attach" to create live ssh connections to master VM …
> [Standalone] Allow to login worker VMs through pub key

- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/standalone.py
> Allow to load a custom ssh key on 'lithops attach'

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
> Move "is instance ready" logic to standalone backends

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/version.py
> [standalone] Wait vm to become ready on lithops attach

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/vm/vm.py
> [VM] Fix VM standalone backend to recent changes

- lithops/storage/backends/infinispan/infinispan.py
Hi, this improves a little bit the Infinispan rest backend.
`verify` isn't 100% ok but better than before. …
> update for Infinispan

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> fix ibm_vpc backend

- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
This will allows to pass custom user_data (CloudConfig) to backend VMs …
> [Standalone] Extrapolate user data on backends

- CHANGELOG.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/ibm_vpc.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/util/ssh_client.py
> Allow to start workers with a public key instead of using a password

- CHANGELOG.md
- lithops/serverless/backends/aws_lambda/aws_lambda.py
> [AWS Lambda] Allow to delete functions from other lithops versions

- lithops/worker/jobrunner.py
> Do not clean tmp dir

- lithops/scripts/cli.py
> Add progress bar to "lithops storage put/get" command

- CHANGELOG.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
> Disable ssh key verification in IBM VPC

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
- lithops/util/ssh_client.py
> add ssh key verification

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> added exception filtering

- CHANGELOG.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/util/ssh_client.py
> Raise exception when the ssh key is not valid

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
Key id is not mandatory for key pair validation.
Checking only if specified private key is a pair for one of the public keys configured for the vm instance …
> key_id is not mandatory for validation

- lithops/serverless/backends/aws_lambda/aws_lambda.py
> Minor fix listing runtimes on aws lambda

- lithops/serverless/backends/aws_lambda/aws_lambda.py
> [AWS lambda] avoid exception if the function is already deployed

- CHANGELOG.md
- lithops/serverless/backends/aws_lambda/aws_lambda.py
Fix issue in AWS Lambda backend
it. …
> [AWS Lambda] wait until "layer builder" function is active

- CHANGELOG.md
- docs/source/cli.rst
- lithops/scripts/cli.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- runtime/aws_lambda/README.md
Allow to create container runtimes whose names contain '.', '/' and '_'
Add missing CLI docs …
> [AWS Lambda] Allow to create container runtimes whose names contain '.', '/' and '_'

- docs/source/configuration.rst
- docs/source/functions.md
1. Added missing quotes in configuration dictionary in Python sample code.
2. Fixed function name in functions.md
person who …
> Fix Python sample code in docs

- CHANGELOG.md
- docs/source/cli.rst
- lithops/scripts/cli.py
- runtime/aws_lambda/Dockerfile.arm64
- runtime/code_engine/README.md
- runtime/gcp_cloudrun/README.md
- runtime/ibm_cf/README.md
- runtime/knative/README.md
- runtime/kubernetes/README.md
> Add aws lambda arm dockerfile example

- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- runtime/README.md
- runtime/aliyun_fc/README.md
- runtime/aws_lambda/Dockerfile.arm64
- runtime/aws_lambda/README.md
> add debug message when deploying the runtime

- examples/wait.py
- lithops/invokers.py
- lithops/localhost/localhost.py
- lithops/scripts/cli.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- lithops/serverless/serverless.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/wait.py
- Set progressbar to the right percentage of waiting value when using the fexec.wait() method
- Fix wait.py example
- Renamed create_runtime() method to deploy_runtime() to avoid confusion with the build_runtime() method
- Add type hints to wait() and get_result() functions
by me, under the same open source license (unless …
> Set progressbar to the right percentage of waiting value

- lithops/tests/test_storage.py
- lithops/tests/util_func/storage_util.py
> unit tests for storage functions

- docs/source/compute_config/ibm_vpc.md
- lithops/localhost/localhost.py
- runtime/ibm_vpc/Dockerfile.nvidia.cuda
> Add gpu support for standalone backend

- lithops/serverless/backends/aws_lambda/aws_lambda.py
- Improved error handling while waiting for function being deployed …
> [AWS] Refactor, improve error handling

- lithops/serverless/backends/aws_lambda/aws_lambda.py
- Fix: List only runtimes deployed by the current user
it.
(d) I …
> [AWS Lambda] Fix list runtimes

- docs/source/compute_config/aws_batch.md
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_batch/config.py
Added parameter `service_role` in config parameters for those users who cannot/want to user service-linked roles.
person who …
> [AWS Batch] Add 'service_role' param in config

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/wait.py
> Show correct IP in standalone logs

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/master.py
> Add configurable timeout param to vm.wait_ready() method

- CHANGELOG.md
- lithops/monitor.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- Fix host_status_query_count stat
- Do not raise an exception if the runtime is already deployed …
> Fix host_status_query_count stat

- config/config_template.yaml
- docs/source/compute_config/code_engine.md
- lithops/serverless/backends/code_engine/code_engine.py
> added retry on connection exception for ce backend

- config/config_template.yaml
- docs/source/storage_config/ibm_cos.md
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/storage/backends/ibm_cos/config.py
> Enables separate authorization for COS and Compute backends

- lithops/serverless/backends/code_engine/code_engine.py
> Improved except-retry logic

- lithops/serverless/backends/knative/knative.py
> Fix mising CoreV1API

- examples/remote_logging.py
- lithops/multiprocessing/util.py
> Updated live remote logging, added example

- docs/source/compute_config/knative.md
- lithops/constants.py
- lithops/serverless/backends/knative/knative.py
> Allow k8s single node public cluster for knative

- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/config.py
- lithops/serverless/backends/knative/knative.py
- lithops/utils.py
> Fix knative service creation

- CHANGELOG.md
- docs/source/compute_config/aliyun_functions.md
- docs/source/compute_config/code_engine.md
- docs/source/compute_config/k8s_job.md
- docs/source/compute_config/knative.md
- lithops/executors.py
- lithops/scripts/cli.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aliyun_fc/config.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_batch/config.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/azure_functions/config.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_cloudrun/config.py
- lithops/serverless/backends/gcp_functions/config.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/config.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/config.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/config.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- lithops/utils.py
Make sure all temp files during build_runtime are cleaned
Load docker_path only when needed instead of trying to load it always …
> Make sure all temp files during build_runtime are cleaned

- CHANGELOG.md
- docs/source/compute_config/aws_lambda.md
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
- runtime/aws_batch/Dockerfile.python38
- runtime/aws_lambda/Dockerfile.python39
- Added parameters in config for ephemeral storage size and instance env vars
- Add missing dockerfiles for lambda python 3.9 …
> [AWS Lambda] Add config parameters for ephemeral storage and instance env vars

- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_cloudrun/config.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/config.py
- lithops/serverless/backends/knative/knative.py
- lithops/storage/backends/gcp_storage/gcp_storage.py
- lithops/utils.py
- fix k8s backneds default image names
- make sure all runtimes are deleted on clean
- include lithops version in k8s based backends …
> make sure all runtimes are deleted on clean

- lithops/scripts/cli.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- runtime/aws_lambda/Dockerfile.python39
> diplay lithops version on 'lithops runtime list'

- CHANGELOG.md
- docs/source/compute_config/azure_functions.md
- docs/source/storage_config/azure_blob.md
- lithops/constants.py
- lithops/localhost/localhost.py
- lithops/scripts/cli.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aliyun_fc/config.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/azure_functions/config.py
- lithops/serverless/backends/gcp_functions/config.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/standalone/standalone.py
- lithops/storage/backends/aliyun_oss/aliyun_oss.py
- lithops/storage/backends/aliyun_oss/config.py
> Fixes in multiple backends

- lithops/serverless/backends/gcp_functions/gcp_functions.py
> wait function deleted on gcp functions

- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
> delete all lambda runtimes on clean

- CHANGELOG.md
- lithops/serverless/backends/aws_batch/config.py
Updated AWS Batch job resource limits
it. …
> [AWS Batch] Update aws batch limits

- lithops/serverless/backends/azure_functions/azure_functions.py
> show invocation error on azure

- lithops/job/partitioner.py
- lithops/tests/test_map_reduce.py
- lithops/tests/util_func/map_util.py
- lithops/worker/jobrunner.py
> Overwrite chunk information

- CHANGELOG.md
- docs/source/compute_config/knative.md
- lithops/job/partitioner.py
- lithops/serverless/backends/knative/config.py
- lithops/serverless/backends/knative/knative.py
- lithops/tests/test_map_reduce.py
- lithops/tests/util_func/map_util.py
- lithops/utils.py
- lithops/worker/jobrunner.py
- runtime/gcp_cloudrun/README.md
- runtime/knative/README.md
> Allow to use Kourier as ingress in knative

- lithops/libs/openwhisk/client.py
> Show debug message instead of exception in OW

- lithops/serverless/backends/azure_functions/azure_functions.py
> [Azure Functions] raise exception on invocation

- lithops/serverless/backends/aws_lambda/config.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/azure_functions/config.py
- lithops/serverless/backends/azure_functions/entry_point.py
- lithops/utils.py
- runtime/azure_functions/README.md
- runtime/azure_functions/requirements.txt
> Add more config parameters to azure functions

- CHANGELOG.md
- config/README.md
- docs/source/compute_config/azure_containers.md
- lithops/constants.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/azure_containers/__init__.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_containers/config.py
- lithops/serverless/backends/azure_containers/entry_point.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/azure_functions/config.py
- runtime/README.md
- runtime/azure_containers/Dockerfile
- runtime/azure_containers/README.md
- runtime/gcp_cloudrun/README.md
- runtime/ibm_cf/README.md
New Lithops backend for [Azure Container Apps](https://azure.microsoft.com/en-us/services/container-apps/) …
> Add new Azure Container Apps backend

- README.md
- docs/source/compute_config/aliyun_functions.md
- docs/source/compute_config/azure_containers.md
- lithops/serverless/backends/aliyun_fc/config.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_containers/config.py
- lithops/serverless/backends/azure_functions/config.py
> update docs and parameters of azure

- CHANGELOG.md
- docs/source/compute_config/aliyun_functions.md
- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/aws_lambda.md
- docs/source/compute_config/azure_containers.md
- docs/source/compute_config/azure_functions.md
- docs/source/compute_config/code_engine.md
- docs/source/compute_config/gcp_cloudrun.md
- docs/source/compute_config/gcp_functions.md
- docs/source/compute_config/ibm_cf.md
- docs/source/compute_config/ibm_vpc.md
- docs/source/compute_config/k8s_job.md
- docs/source/compute_config/knative.md
- docs/source/compute_config/localhost.md
- docs/source/compute_config/openwhisk.md
- docs/source/compute_config/vm.md
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_containers/config.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/utils.py
> Allow to run Azure functions from a non-linux OS

- docs/source/compute_config/azure_containers.md
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_containers/config.py
> allow private containers on azure

- lithops/serverless/backends/knative/knative.py
> fix memory parsing in knative

- lithops/worker/jobrunner.py
> hide unnecessary byte range

- lithops/job/job.py
- lithops/scripts/cli.py
> add runtime_timeout in runtime_meta

- CHANGELOG.md
- docs/source/compute_config/gcp_cloudrun.md
- docs/source/compute_config/gcp_functions.md
- docs/source/storage_config/gcp_storage.md
- lithops/executors.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_cloudrun/config.py
- lithops/serverless/backends/gcp_functions/config.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/storage/backends/gcp_storage/config.py
- lithops/storage/backends/gcp_storage/gcp_storage.py
delete storage_account adn project_name config params #963  
it.
(d) …
> [GCP] delete unnecessary config params

- docs/source/compute_config/gcp_cloudrun.md
- docs/source/compute_config/gcp_functions.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
> some fixes in gcp and ce

- lithops/storage/backends/gcp_storage/gcp_storage.py
> add missing logic in gcp_storage

- CHANGELOG.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
> [CE] fix runtime_timeout parameter

- docs/api_futures.md
- docs/source/api_stats.rst
- docs/source/compute_config/azure_containers.md
- lithops/executors.py
- lithops/wait.py
- lithops/worker/handler.py
- lithops/worker/utils.py
- Add peak memory stat in Lithops worker #970 
- Add option to disable progress bar #971
- Docs update …
> add peak memory stat

- docs/source/api_stats.rst
- lithops/future.py
- lithops/job/job.py
- lithops/worker/handler.py
- lithops/worker/jobrunner.py
> move peak_memory measurement to jobrunner

- CHANGELOG.md
> update changelog to 2.7.0

- CHANGELOG.md
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
> [IBM VPC] Infer zone_name from subnet

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
> fix vpc cache data and threadpool creation

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/master.py
> Update ec2 default ubuntu image to 22.04

- docs/conf.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> show navbar in docs

- CHANGELOG.md
- lithops/serverless/backends/aws_batch/config.py
- lithops/serverless/backends/gcp_functions/config.py
> [GCP Functions] Add Python3.10 runtime compatibility

- CHANGELOG.md
- lithops/multiprocessing/context.py
This PR fixes the issue #989 .
it. …
> Fix cpu_count from multiprocessing API

- runtime/aws_batch/conda.Dockerfile
- runtime/aws_lambda/conda/conda-python3-9.Dockerfile
- runtime/aws_lambda/conda/lithops-env-py39.yml
Added conda runtime Dockerfiles for AWS backends.
it.
(d) I …
> [AWS] Conda runtimes for AWS backends

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
> Print compatible python versions as list

- lithops/config.py
- lithops/executors.py
- lithops/future.py
- lithops/invokers.py
- lithops/job/job.py
- lithops/localhost/localhost.py
- lithops/localhost/runner.py
- lithops/multiprocessing/connection.py
- lithops/multiprocessing/managers.py
- lithops/plots.py
- lithops/scripts/cleaner.py
- lithops/scripts/cli.py
- lithops/standalone/keeper.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
- lithops/storage/storage.py
- lithops/util/ibm_token_manager.py
- lithops/worker/jobrunner.py
- lithops/worker/status.py
- lithops/worker/utils.py
> some flake8 fixes

- lithops/serverless/backends/code_engine/code_engine.py
> handle code engine 409 error

- CHANGELOG.md
- lithops/serverless/backends/gcp_functions/config.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
> [GCP Functions] Fix runtime_build command

- docs/source/compute_config/gcp_cloudrun.md
- docs/source/compute_config/gcp_functions.md
> Update gcp docs

- CHANGELOG.md
- config/README.md
- docs/source/compute_config/localhost.md
- docs/source/storage_config/infinispan.md
- lithops/storage/backends/infinispan/infinispan.py
> [Infinispan] Fix infinispan storage backend

- lithops/job/serialize.py
> [Core] Extend serializer

- CHANGELOG.md
- examples/call_async_class.py
- examples/call_async_cython.py
- lithops/job/serialize.py
Removed some redundant code
it. …
> [Core] Reorganize serializer logic

- CHANGELOG.md
- examples/map_internal.py
- lithops/future.py
- lithops/serverless/backends/ibm_cf/config.py
- lithops/serverless/backends/openwhisk/config.py
- lithops/worker/handler.py
- lithops/worker/jobrunner.py
This will substantially reduce the total amount of GET requests from the client to the storage backend …
> [Core] Include function result in the status file if it is < 8KB

- lithops/storage/backends/localhost/localhost.py
- lithops/tests/test_storage.py
- lithops/tests/tests_main.py
> [Tests] Fix storage tests

- CHANGELOG.md
- lithops/constants.py
- lithops/localhost/localhost.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
> Allow to delete runtime from different lithops versions

- CHANGELOG.md
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/openwhisk.py
> [Serverless] Allow to delete runtimes from different lithops versions

- CHANGELOG.md
- docs/source/compute_config/gcp_cloudrun.md
- lithops/serverless/backends/aws_batch/config.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_cloudrun/config.py
> [GCP CloudRun] Allow to set min_workers in the autoscaler

- CHANGELOG.md
- docs/source/compute_config/azure_functions.md
- docs/source/compute_config/gcp_functions.md
- docs/source/compute_config/vm.md
- lithops/invokers.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/azure_functions/config.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_cloudrun/entry_point.py
- lithops/serverless/backends/gcp_functions/entry_point.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
> [GCP Cloud Functions] Added https trigger

- docs/source/compute_config/azure_containers.md
- docs/source/compute_config/azure_functions.md
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_containers/config.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/version.py
> [Azure] Update azure docs

- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_lambda.md
- docs/source/storage_config/aws_s3.md
- docs/source/storage_config/ceph.md
- docs/source/storage_config/minio.md
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_batch/config.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/storage/backends/aws_s3/aws_s3.py
- lithops/storage/backends/aws_s3/config.py
- lithops/storage/backends/ceph/ceph.py
- lithops/storage/backends/ceph/config.py
- lithops/storage/backends/minio/config.py
- lithops/storage/backends/minio/minio.py
I've added an option to pass a session token from AWS credentials. Session tokens are included f.e. in credentials for student accounts.
Tested it with `lithops test` with credentials from my AWS Academy account.
Also included info about those changes in docs.
--- …
> [AWS] Added session token as optional

- .github/workflows/main.yml
- CHANGELOG.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/storage/backends/localhost/localhost.py
> [localhost] Fix localhost storage backend head method

- .github/workflows/main.yml
- lithops/serverless/backends/azure_functions/azure_functions.py
> [Azure Functions] Fix worker name

- lithops/wait.py
> Fix typo in docstring

- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/k8s/k8s.py
> Fix access to storage config

- docs/source/storage_config/aws_s3.md
- docs/source/testing.rst
- lithops/config.py
- lithops/scripts/cli.py
- lithops/serverless/serverless.py
- lithops/standalone/standalone.py
- lithops/storage/backends/aws_s3/aws_s3.py
- lithops/storage/backends/aws_s3/config.py
- lithops/storage/storage.py
- lithops/storage/utils.py
- lithops/tests/test_map_reduce.py
- lithops/tests/test_storage.py
- lithops/tests/tests_main.py
- lithops/tests/util_func/storage_util.py
> Fix aws s3 config

- CHANGELOG.md
- lithops/job/partitioner.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/config.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/config.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- lithops/utils.py
If the credentials are present in config
it. …
> [IBM] Automatically login to the container registry on "lithops container build"

- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/openwhisk/openwhisk.py
> [Aliyun] Fix runtime name

- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/openwhisk/openwhisk.py
> [IBM CF] Fix config param

- lithops/config.py
- lithops/localhost/localhost.py
- lithops/worker/handler.py
> [Config] Add missing return statement

- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/k8s.py
> [k8s] Fix get_metadata method

- CHANGELOG.md
- lithops/scripts/cli.py
- runtime/kubernetes/README.md
> [Cli] Fix wrong config in "lithops runtime update"

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/standalone.py
> [Standalone] Fix missing private IP address

- lithops/executors.py
- lithops/future.py
- lithops/storage/storage.py
Fix typos in docstrings, add missing parameters, and remove unused ones …
> Docstrings enhancements

- CHANGELOG.md
- docs/source/compute_config/ibm_vpc.md
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Automatically get the ubuntu image ID

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Change VPC key name

- CHANGELOG.md
- docs/source/compute_config/ibm_vpc.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/config.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
> [IBM VPC] Added 'region' & Reuse floating IP

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Added missing home

- CHANGELOG.md
- docs/source/compute_config/ibm_vpc.md
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Renamed profile_name to worker_profile_name

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Allow clean() from code

- CHANGELOG.md
- lithops/executors.py
> [Executor] Allow to set all the compute backend params programatically

- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/ibm_vpc.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC & AWS EC2] Fixes

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/standalone.py
> [AWS EC2] Minor change

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
> [Standalone] Reduce redundant logic

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [Standalone] Make sure only VMs from the given VPC are deleted

- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
> [AWS EC2] Fix get_instance_data method

- CHANGELOG.md
- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/aws_lambda.md
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [AWS EC2] Automatically create VPC resources

- CHANGELOG.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [AWS EC2] Make sure all resources are removed

- CHANGELOG.md
- lithops/config.py
- lithops/executors.py
- lithops/scripts/cli.py
- lithops/storage/storage.py
- lithops/tests/tests_main.py
> [Executor] Allow to pass the config file location in the FunctionExecutor()

- CHANGELOG.md
- docs/source/storage_config/aliyun_oss.md
- docs/source/storage_config/aws_s3.md
- docs/source/storage_config/azure_blob.md
- docs/source/storage_config/ceph.md
- docs/source/storage_config/gcp_storage.md
- docs/source/storage_config/ibm_cos.md
- docs/source/storage_config/minio.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/storage/backends/aws_s3/aws_s3.py
- lithops/storage/backends/aws_s3/config.py
- lithops/storage/backends/ceph/ceph.py
- lithops/storage/backends/ceph/config.py
- lithops/storage/backends/ibm_cos/config.py
- lithops/storage/backends/ibm_cos/ibm_cos.py
- lithops/storage/backends/minio/config.py
- lithops/storage/backends/minio/minio.py
- lithops/storage/storage.py
> [Storage] Auto create the storage bucket if not provided

- CHANGELOG.md
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Reuse floating IPs for public gateways

- CHANGELOG.md
- docs/source/compute_config/code_engine.md
- docs/source/compute_config/ibm_cf.md
- lithops/serverless/backends/ibm_cf/config.py
> [IBM CF] Allow to configure CF using "region" parameter

- docs/source/cli.rst
- docs/source/compute_config/code_engine.md
- docs/source/compute_config/ibm_cf.md
- docs/source/compute_config/ibm_vpc.md
- docs/source/storage_config/aws_s3.md
- docs/source/storage_config/ceph.md
- docs/source/storage_config/ibm_cos.md
- docs/source/storage_config/minio.md
- lithops/scripts/cli.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/ibm_cf/config.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/storage/backends/ibm_cos/config.py
- runtime/ibm_vpc/README.md
> [IBM] Allow to set region under the 'ibm' section

- CHANGELOG.md
- docs/source/compute_config/ibm_vpc.md
- lithops/config.py
- lithops/constants.py
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
> [IBM VPC] Added build_image() method for building VM images

- CHANGELOG.md
- docs/source/compute_config/aliyun_functions.md
- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/aws_lambda.md
- docs/source/compute_config/azure_containers.md
- docs/source/compute_config/azure_functions.md
- docs/source/storage_config/aliyun_oss.md
- docs/source/storage_config/aws_s3.md
- lithops/executors.py
- lithops/scripts/cli.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aliyun_fc/config.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_batch/config.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
- lithops/serverless/backends/ibm_cf/config.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/storage/backends/aliyun_oss/aliyun_oss.py
- lithops/storage/backends/aliyun_oss/config.py
- lithops/storage/backends/aws_s3/aws_s3.py
- lithops/storage/backends/aws_s3/config.py
> [AWS] Allow 'region' param instead of 'region_name' for compatibility

- CHANGELOG.md
- docs/source/cli.rst
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/standalone.py
- lithops/tests/tests_main.py
> [Cli] Add new 'lithops image list' command

- CHANGELOG.md
- config/README.md
- config/config_template.yaml
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/code_engine.md
- docs/source/compute_config/ibm_cf.md
- docs/source/compute_config/ibm_vpc.md
- docs/source/storage_config/ibm_cos.md
- lithops/libs/openwhisk/client.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/config.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- lithops/serverless/serverless.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/storage/backends/ibm_cos/config.py
- lithops/storage/backends/ibm_cos/ibm_cos.py
- lithops/util/ibm_token_manager.py
- runtime/code_engine/requirements.txt
This allows to configure CF using this:
```yaml
ibm:
iam_api_key: XXXX
region : eu-gb
resource_group_id: XXXX
```
person who …
> [IBM CF] Automatically create a CF namespace if not provided

- CHANGELOG.md
- docs/source/compute_config/code_engine.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/util/ibm_token_manager.py
> [IBM] Add refresh_token() method in token manager

- lithops/serverless/backends/ibm_cf/ibm_cf.py
> [IBM CF] Minor fix in invoke

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Make vpc_key more unique

- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- runtime/ibm_vpc/README.md
> Make ssh_key more unique

- CHANGELOG.md
- lithops/util/ssh_client.py
> [SSH Cli] Fix issue with RSA keys

- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/ibm_vpc/config.py
- runtime/kubernetes/Dockerfile
- runtime/kubernetes/README.md
> [Standalone] Prevent misconfiguration

- CHANGELOG.md
- lithops/serverless/backends/aws_lambda/config.py
> [AWS Lambda] Add support for python 3.10 runtimes

- docs/source/compute_config/azure_containers.md
- docs/source/compute_config/azure_functions.md
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/utils.py
> [Azure] docs update

- config/README.md
- docs/source/compute_backends.rst
- docs/source/compute_config/azure_vms.md
- docs/source/configuration.rst
- docs/source/execution_modes.rst
- docs/source/supported_clouds.rst
> [Azure] Update docs

- lithops/standalone/backends/azure_vms/azure_vms.py
> [Azure VMs] Delete Public IP address

- lithops/wait.py
> [Wait] Fix log message formatting

- CHANGELOG.md
- lithops/tests/tests_main.py
> [Tests] Fix broken links of testing files

- CHANGELOG.md
- README.md
- docs/conf.py
- docs/source/compute_config/azure_vms.md
- docs/source/functions.md
- docs/source/monitoring.rst
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Add Madrid (Spain) region

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [Azure Container APPs] Make sure the lithops worker app is deployed

- config/README.md
- docs/source/storage_config/ibm_cos.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/util/ibm_token_manager.py
> [Standalone] Improve list_images()

- CHANGELOG.md
- docs/source/compute_config/code_engine.md
- docs/source/compute_config/ibm_cf.md
- lithops/libs/openwhisk/client.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/config.py
- lithops/serverless/backends/ibm_cf/config.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- runtime/code_engine/requirements.txt
- setup.py
> [Code Engine] Automatically create a new project if not provided in config

- docs/source/compute_config/aws_lambda.md
- lithops/serverless/backends/aws_lambda/config.py
> [AWS Lambda] Pin urllib3 version

- CHANGELOG.md
- examples/multiprocessing/pipe.py
- lithops/multiprocessing/connection.py
- lithops/multiprocessing/util.py
> [Multiprocessing] Check redis connection before starting to submit jobs

- CHANGELOG.md
- lithops/storage/backends/infinispan/infinispan.py
- lithops/storage/backends/infinispan_hotrod/infinispan_hotrod.py
- lithops/storage/backends/localhost/localhost.py
- lithops/storage/backends/redis/redis.py
- lithops/storage/backends/swift/swift.py
> [Redis] Fix redis storage backend

- README.md
- lithops/multiprocessing/util.py
> [Multiprocessing] Reuse redis instance

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Make sure an amd64 image is retrieved

- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Minnor fix listing images

- CHANGELOG.md
- lithops/serverless/backends/azure_functions/config.py
- lithops/serverless/backends/gcp_functions/config.py
- lithops/serverless/backends/ibm_cf/config.py
- runtime/ibm_cf/Dockerfile.slim
> Add support for python 3.11

- .github/workflows/main.yml
- CONTRIBUTING.md
- README.md
- docs/source/cli.rst
- docs/source/compute_config/aliyun_functions.md
- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/aws_lambda.md
- docs/source/compute_config/azure_containers.md
- docs/source/compute_config/azure_functions.md
- docs/source/compute_config/azure_vms.md
- docs/source/compute_config/code_engine.md
- docs/source/compute_config/gcp_cloudrun.md
- docs/source/compute_config/gcp_functions.md
- docs/source/compute_config/ibm_cf.md
- docs/source/compute_config/ibm_vpc.md
- docs/source/compute_config/k8s_job.md
- docs/source/compute_config/knative.md
- docs/source/compute_config/localhost.md
- docs/source/compute_config/openwhisk.md
- docs/source/compute_config/vm.md
- docs/source/contributing.rst
- docs/source/testing.rst
- lithops/scripts/cli.py
> update lithops hello command

- CHANGELOG.md
- docs/source/compute_config/azure_vms.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/azure_vms/azure_vms.py
> [Azure VMs] Allow listing images

- CHANGELOG.md
- lithops/executors.py
- lithops/serverless/backends/openwhisk/config.py
> [Openwhisk] Include the default python 3.11 runtime

- lithops/executors.py
- lithops/invokers.py
> Add kwargs in the localhost executor

- CHANGELOG.md
- docs/source/compute_config/code_engine.md
- lithops/serverless/backends/code_engine/code_engine.py
> [CodeEngine] Create the CE project only when necessary

- lithops/serverless/backends/code_engine/code_engine.py
> [CE] Return namespace

- CHANGELOG.md
- lithops/libs/openwhisk/client.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
> [IBM CF] Create the CF namespace only when necessary

- docs/source/compute_config/oracle_functions.md
- docs/source/storage_config/oracle_oss.md
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/oracle_f/config.py
- lithops/serverless/backends/oracle_f/entry_point.py
- lithops/serverless/backends/oracle_f/oracle_f.py
- runtime/gcp_cloudrun/README.md
- runtime/ibm_vpc/README.md
> [OCI Functions] Remove python3.8 dependency

- lithops/serverless/backends/oracle_f/config.py
- lithops/serverless/backends/oracle_f/oracle_f.py
- lithops/storage/backends/oracle_oss/config.py
- lithops/storage/backends/oracle_oss/oracle_oss.py
> [OCI Functions] Add supported python versions

- docs/source/storage_config/oracle_oss.md
- lithops/invokers.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aliyun_fc/entry_point.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/serverless.py
- lithops/storage/backends/oracle_oss/config.py
- lithops/storage/backends/oracle_oss/oracle_oss.py
> [Oracle OSS] Implement missing create_bucket() method

- docs/source/compute_config/oracle_functions.md
- docs/source/storage_config/oracle_oss.md
- lithops/serverless/backends/oracle_f/config.py
- lithops/serverless/backends/oracle_f/entry_point.py
- lithops/serverless/backends/oracle_f/oracle_f.py
- lithops/storage/backends/oracle_oss/config.py
- lithops/storage/backends/oracle_oss/oracle_oss.py
- runtime/oracle_f/Dockerfile
Implemented missing methods:
- _format_image_name()
- _build_default_runtime()
- pre_invoke()
- list_runtimes()
- delete_runtime()
Removed unnecessary methods:
- unformat_function_name()
-  _create_handler_bin()
- _application_exists()
Other fixes
permitted to submit …
> [Oracle Functions] Implement missing methods

- lithops/job/job.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/entry_point.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/oracle_f/oracle_f.py
- lithops/worker/handler.py
- runtime/kubernetes/Dockerfile
- runtime/kubernetes/Dockerfile.conda
> [Oracle] Include internal invoke client

- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/config.py
- lithops/serverless/backends/k8s/entry_point.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- runtime/kubernetes/Dockerfile
- runtime/kubernetes/Dockerfile.conda
> Automatically login to the container registry

- CHANGELOG.md
- lithops/job/serialize.py
> [Serializer] Fixed issue in serializer when "include_modules" config var is set

- CHANGELOG.md
- lithops/serverless/backends/code_engine/code_engine.py
> [CodeEngine] Minor fixes

- lithops/serverless/backends/aws_lambda/aws_lambda.py
> [AWS Lambda] Use username in federated users as function key

- lithops/serverless/backends/k8s/entry_point.py
> [k8s] Make sure callids is properly set

- config/README.md
- docs/source/compute_backends.rst
- docs/source/compute_config/aliyun_functions.md
- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_lambda.md
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/k8s/entry_point.py
- setup.py
> Include boto3 lib in the default installation

- docs/source/execution_modes.rst
> execution modes docs update

- CHANGELOG.md
- lithops/job/job.py
- runtime/ibm_cf/Dockerfile.slim
- runtime/ibm_cf/requirements.txt
> [Job] Fixed max data size in the invocation payload

- lithops/job/job.py
- lithops/scripts/cleaner.py
- lithops/storage/utils.py
- lithops/util/joblib/lithops_backend.py
> [Joblib] Update joblib backend for newer versions of joblib

- CHANGELOG.md
- lithops/localhost/localhost.py
- lithops/multiprocessing/context.py
> [Multiprocessing] Fix cpu_count

- CHANGELOG.md
- lithops/constants.py
- lithops/localhost/localhost.py
- lithops/scripts/cli.py
- lithops/standalone/worker.py
- lithops/util/joblib/lithops_backend.py
- lithops/worker/handler.py
> [Worker] Add more flexebility in setting work queues

- lithops/constants.py
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/utils.py
- runtime/aws_ec2/README.md
- runtime/ibm_vpc/README.md
> [Standalone] Include potentially missing libs

- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/worker.py
> [Standalone] Make distinction between worker instance types

- CHANGELOG.md
- docs/source/compute_config/ibm_vpc.md
- lithops/invokers.py
- lithops/scripts/cli.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/k8s/entry_point.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/vm.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
- lithops/worker/jobrunner.py
- setup.py
- Added new 'lithops job list' command for standalone backends
- Added new 'lithops worker list' command for standalone backends
For example:
```
josep@ubuntu:~$ lithops job list -b ibm_vpc
2023-11-03 17:11:03,052 [INFO] config.py:139 -- Lithops v3.0.2.dev0 - Python3.10
2023-11-03 17:11:03,245 [INFO] ibm_vpc.py:92 -- IBM VPC client created - Region: eu-gb
2023-11-03 17:11:11,866 [INFO] cli.py:680 -- Listing jobs submitted to VM instance lithops-master-b2ae13 (158.175.185.335)
Job ID         Function Name    Submitted                Runtime      Total Tasks  Status
-------------  ---------------  -----------------------  ---------  -------------  --------
d7d1f0-0-A000  hello()          2023-11-03 16:06:09 UTC  python3                1  done
cc7d66-0-A000  hello()          2023-11-03 …
```
> [Standalone] Add new cli commands for listing jobs and workers

- CHANGELOG.md
- docs/source/cli.rst
- lithops/scripts/cli.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
> [cli] Update docs

- lithops/monitor.py
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
> [standalone] change name of default id_rsa key

- CHANGELOG.md
- docs/source/compute_config/localhost.md
- lithops/constants.py
- lithops/localhost/v1/localhost.py
- lithops/localhost/v2/localhost.py
- lithops/localhost/v2/service.py
- lithops/monitor.py
- lithops/standalone/master.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
> [localhost] Get the correct docker path in case of container execution

- CHANGELOG.md
- lithops/serverless/backends/k8s/k8s.py
> [k8s] Limit size of worker name as the maximum allowed is 63 chars

- CHANGELOG.md
- lithops/serverless/backends/k8s/k8s.py
> [k8s] Limit the size of the "user" label as the maximum allowed is 63 chars

- lithops/serverless/backends/k8s/k8s.py
> [k8s] hash user name as it can contain invalid parameters

- CHANGELOG.md
- lithops/job/job.py
- lithops/job/serialize.py
- lithops/libs/multyvac/module_dependency.py
- lithops/util/joblib/lithops_backend.py
> [Serializer] Improve serializer performance when include_modules is set in config

- CHANGELOG.md
- examples/sklearn_job_3.py
- lithops/util/joblib/lithops_backend.py
> [Joblib] Fix shared objects utility when multiple maps run from the same executor

- CHANGELOG.md
- docs/source/api_stats.rst
> Fix stats description

- CHANGELOG.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/azure_vms.md
- docs/source/compute_config/ibm_vpc.md
- lithops/invokers.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/code_engine/entry_point.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/k8s/entry_point.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/standalone/__init__.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/azure_vms/config.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/backends/vm/config.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/util/ssh_client.py
Automatically retrieve the CPU_COUNT from the VM in case `worker_processes` is not set in config …
> [Standalone] Automatically retrieve the CPU_COUNT from the VMs

- lithops/standalone/master.py
> [standalone] do not get worker instance type in consume

- CHANGELOG.md
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/standalone.py
- lithops/storage/backends/aliyun_oss/aliyun_oss.py
- lithops/storage/backends/aws_s3/aws_s3.py
- lithops/storage/backends/azure_storage/azure_storage.py
- lithops/storage/backends/ceph/ceph.py
- lithops/storage/backends/gcp_storage/gcp_storage.py
- lithops/storage/backends/ibm_cos/ibm_cos.py
- lithops/storage/backends/infinispan/infinispan.py
- lithops/storage/backends/infinispan_hotrod/infinispan_hotrod.py
- lithops/storage/backends/localhost/localhost.py
- lithops/storage/backends/minio/minio.py
- lithops/storage/backends/oracle_oss/oracle_oss.py
- lithops/storage/backends/redis/redis.py
- lithops/storage/backends/swift/swift.py
- lithops/storage/cloud_proxy.py
- lithops/storage/storage.py
- lithops/util/joblib/lithops_backend.py
Include "Config" parameter to download_file() and upload_file() methods for boto3 related backends
person who certified (a), (b) …
> [Storage] Include "config" parameter to download and upload methods

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/serverless/backends/aliyun_fc/aliyun_fc.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/azure_functions/azure_functions.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/gcp_functions/gcp_functions.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/openwhisk/openwhisk.py
- lithops/serverless/backends/oracle_f/oracle_f.py
[Cli] Include 'worker name' in the 'lithops runtime list' cmd
[AWS Lambda] Renamed function name to "lithops-worker-xxxx-v310-yyyyyy" #1210 
(c) The contribution was provided directly to me by …
> [Cli] Include worker name in the lithops runtime list cmd

- CHANGELOG.md
- docs/source/compute_config/aws_lambda.md
- lithops/serverless/backends/aws_lambda/aws_lambda.py
> [AWS Lambda] Created 'namespace' config key to virtually separate worker deployments

- CHANGELOG.md
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
> [Standalone] Notify stop status when the VM is dismantled

- CHANGELOG.md
- lithops/scripts/cleaner.py
- lithops/tests/util_func/map_util.py
- lithops/utils.py
> [Partitioner] Fix partitioner

- CHANGELOG.md
- docs/conf.py
> Changelog update

- lithops/storage/backends/gcp_storage/gcp_storage.py
Solving related issue for GCP Storage.
Previously, the `Conflict` exception was thrown when a bucket could not be created because it already existed.
The bucket is now verified to exist before attempting to create it.
- `Conflict` will not be thrown.
- If we do not find the bucket (`NotFound`), it will be created.
- If we try to access a bucket from another tenant, the `Forbidden` exception will be thrown.
license and I have the right under that …
> [GCP Storage] Resolving issue #1220

- lithops/standalone/backends/aws_ec2/aws_ec2.py
> [AWS EC2] Create public and private subnets

- CHANGELOG.md
- docs/source/cli.rst
- docs/source/compute_config/ibm_vpc.md
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- setup.py
This allows to execute VMs into a specific Zone
it. …
> [IBM VPC] Add Zone config parameter

- CHANGELOG.md
- config/README.md
- docs/source/compute_config/ibm_cf.md
- lithops/standalone/standalone.py
> [Standalone] Fix issue with a wrong value of "chunksize"

- CHANGELOG.md
- lithops/serverless/backends/code_engine/code_engine.py
- runtime/code_engine/Dockerfile.conda
> [IBM CE] Fix missing parameter on clean

- CHANGELOG.md
- lithops/serverless/backends/code_engine/code_engine.py
- runtime/code_engine/Dockerfile.conda
- runtime/code_engine/Dockerfile.githubci
- runtime/code_engine/requirements.txt
> [Code Engine] Get error message in case of container failure

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
> [IBM VPC] Store the cache file based on the zone

- lithops/plots.py
> [plots] include function start and end in the plots

- lithops/plots.py
- runtime/code_engine/Dockerfile.conda
- runtime/code_engine/requirements.txt
> [CE] Update requirements file

- CHANGELOG.md
- lithops/executors.py
- lithops/plots.py
> [Plots] Allow to set the figure size of the plots

- lithops/serverless/backends/k8s/k8s.py
> Fix error with node name assignation

- CHANGELOG.md
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
- lithops/util/ssh_client.py
> [Standalone] Fix issue appearing when the invocation payload is too big

- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Increase retry timeout

- CHANGELOG.md
- lithops/invokers.py
> [Invoker] Fix customized_runtime temp path

- lithops/invokers.py
- lithops/worker/utils.py
> change default tmp dir for runtime_include_function

- docs/source/compute_config/aws_lambda.md
- docs/source/compute_config/azure_containers.md
- docs/source/compute_config/code_engine.md
- docs/source/compute_config/gcp_cloudrun.md
- docs/source/compute_config/ibm_cf.md
- docs/source/compute_config/openwhisk.md
- docs/source/compute_config/oracle_functions.md
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/worker/handler.py
- lithops/worker/utils.py
- [IBM VPC] Increase the total number of available IPs in the private network
- [Statistics] Make psutil backward compatible …
> [IBM VPC] Increase the total number of available IPs in the private network

- CHANGELOG.md
- docs/source/compute_config/ibm_vpc.md
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [IBM VPC] Added a new parameter to enable/disable resource existence check in the platform

- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/ibm_vpc.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
> [AWS EC2] Restore default IPs values on stop

- CHANGELOG.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
> [Standalone] Do not stop the VM immediately after a job in the Consume mode

- CHANGELOG.md
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/worker.py
> [Standalone] Remove the workers from the list if delete_on_dismantle is True

- CHANGELOG.md
- config/config_template.yaml
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/azure_vms.md
- docs/source/compute_config/ibm_vpc.md
- lithops/constants.py
- lithops/localhost/v1/localhost.py
- lithops/localhost/v2/localhost.py
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/runner.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
- lithops/util/ssh_client.py
- setup.py
- [Standalone] Use redis in the master VM to store all the relevant data about jobs and workers
- [Standalone] Use redis to store the work queues for the workers
- [Standalone] Improved resiliency
- [Standalone] Improved worker processes granularity when processing tasks from the work queue
- [CLI] Show the timestamp in the local timezone format on "lithops job list"
work with …
> [Standalone] Use redis in master VM for workers and jobs data, and for queues

- CHANGELOG.md
- lithops/invokers.py
- lithops/standalone/master.py
- lithops/standalone/runner.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
- lithops/util/ssh_client.py
- lithops/worker/utils.py
> [Standalone] Write the done file when the job is killed

- lithops/standalone/master.py
- lithops/standalone/utils.py
- lithops/worker/utils.py
> [Worker] Change function caching folder

- CHANGELOG.md
- lithops/config.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/azure_vms/config.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/backends/vm/config.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/worker.py
> [CLI] Show worker creation timestamp and ttd in lithops worker list

- lithops/serverless/backends/k8s/k8s.py
> [K8s] Fix task granularity calculation 

- lithops/standalone/master.py
- lithops/worker/utils.py
> [Standalone] Minor fix in work queue

- lithops/invokers.py
- lithops/monitor.py
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/code_engine/code_engine.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/standalone/standalone.py
> [Standalone] Show number of required workers and instance type

- CHANGELOG.md
- lithops/scripts/cli.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/standalone.py
- runtime/aws_ec2/README.md
- runtime/ibm_vpc/README.md
> [CLI] Added "--include" parameter in "lithops image build"

- lithops/standalone/master.py
- lithops/standalone/runner.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
> [Standalone] restart worker service on failure

- docs/source/compute_config/gcp_cloudrun.md
- docs/source/compute_config/gcp_functions.md
- lithops/constants.py
- lithops/serverless/backends/gcp_functions/config.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
- lithops/standalone/utils.py
- lithops/standalone/worker.py
- runtime/aws_ec2/README.md
- runtime/gcp_functions/README.md
- runtime/gcp_functions/requirements.txt
- runtime/ibm_vpc/README.md
> runtime docs update

- CHANGELOG.md
- config/README.md
- runtime/aliyun_fc/README.md
- runtime/aliyun_fc/requirements.txt
- runtime/aws_lambda/README.md
- runtime/azure_containers/README.md
- runtime/azure_functions/README.md
- runtime/azure_functions/requirements.txt
- runtime/code_engine/README.md
- runtime/gcp_cloudrun/README.md
- runtime/gcp_functions/README.md
- runtime/knative/README.md
- runtime/kubernetes/README.md
- runtime/openwhisk/README.md
> Update runtime docs and changelog

- CHANGELOG.md
- lithops/serverless/backends/aws_lambda/aws_lambda.py
Fix https://github.com/lithops-cloud/lithops/issues/1290
it.
(d) I …
> [AWS Lambda] Fix runtime deletion with "lithops runtime delete" command

- lithops/serverless/backends/aws_lambda/aws_lambda.py
> [AWS Lambda] specify linux/amd64 platform when building a runtime

- lithops/config.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/storage/storage.py
- lithops/storage/utils.py
> [AWS Lambda] Reduce sts overhead

- lithops/serverless/backends/k8s/k8s.py
> Fixed runtime units issue

- .github/workflows/on_pull_request.yml
- CONTRIBUTING.md
- lithops/job/serialize.py
- lithops/libs/inspect/__init__.py
- lithops/libs/inspect/inspect.py
- lithops/tests/functions.py
- lithops/tests/test_call_async.py
> [Serializer] Include inspect getmembers_static in Lithops

- CHANGELOG.md
- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/aws_lambda.md
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_batch/config.py
- lithops/serverless/backends/aws_lambda/config.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
> [AWS] Remove the need for access and secret keys in the configuration

- CHANGELOG.md
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/azure_containers/azure_containers.py
- lithops/serverless/backends/gcp_cloudrun/cloudrun.py
- lithops/serverless/backends/k8s/k8s.py
- lithops/serverless/backends/knative/knative.py
- lithops/serverless/backends/oracle_f/oracle_f.py
> [Serverless] Allow to build container runtimes using the MacBook Mx chip

- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/aws_lambda.md
- docs/source/storage_config/aws_s3.md
> [AWS] Update configuration docs

- lithops/serverless/backends/k8s/entry_point.py
> Fixed synchronism error for functions with few tasks

- CHANGELOG.md
- README.md
- docs/source/cli.rst
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/ibm_cf/ibm_cf.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/storage/backends/aws_s3/aws_s3.py
- runtime/aws_ec2/README.md
- runtime/ibm_vpc/README.md
> [aws] make user-key consistent across aws backends

- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/azure_vms/config.py
- lithops/standalone/backends/ibm_vpc/config.py
- lithops/standalone/master.py
- lithops/standalone/utils.py
> [Azure VMs] Fix worker creation and communication

- CHANGELOG.md
- lithops/serverless/backends/azure_containers/azure_containers.py
- [Changelog] Contributors names are in the release notes
it.
(d) I …
> [Azure Containers] Automatically login to the container registry if the credentials are in the config

- .github/workflows/on_pull_request.yml
> include setup.py in the github workflows

- lithops/serverless/backends/aws_lambda/aws_lambda.py
> AWS Lambda delete runtime should have exact match semantics

- docs/source/api_multiprocessing.rst
- docs/source/storage_config/redis.md
- setup.py
> Move redis package into lithops[redis] extra

- docs/source/api_multiprocessing.rst
- docs/source/compute_config/aliyun_functions.md
- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/aws_lambda.md
- docs/source/compute_config/azure_containers.md
- docs/source/compute_config/azure_functions.md
- docs/source/compute_config/azure_vms.md
- docs/source/compute_config/gcp_cloudrun.md
- docs/source/compute_config/gcp_functions.md
- docs/source/compute_config/oracle_functions.md
- docs/source/sklearn_joblib.rst
- docs/source/storage_config/aliyun_oss.md
- docs/source/storage_config/aws_s3.md
- docs/source/storage_config/azure_blob.md
- docs/source/storage_config/ceph.md
- docs/source/storage_config/gcp_storage.md
- docs/source/storage_config/minio.md
- docs/source/storage_config/oracle_oss.md
- docs/source/storage_config/redis.md
> Update installation docs

- lithops/wait.py
> Make progress bar independent of log level

- lithops/monitor.py
> [Monitor] prevent potential keyerror exception

- lithops/future.py
- lithops/monitor.py
> [Monitor] Expose `wait_dur_sec` and `retries` in wait() and get_result()

- lithops/scripts/cli.py
> [cli] allow name in runtime list

- lithops/localhost/v2/localhost.py
- lithops/monitor.py
> [Monitor] Fix potential keyerror

- CONTRIBUTING.md
- lithops/executors.py
- lithops/libs/inspect/inspect.py
- lithops/localhost/__init__.py
- lithops/localhost/v1/localhost.py
- lithops/localhost/v2/localhost.py
- lithops/tests/functions.py
> Fixes for localhost tests

- CHANGELOG.md
- lithops/config.py
- lithops/constants.py
- lithops/executors.py
- lithops/job/serialize.py
- lithops/localhost/__init__.py
- lithops/localhost/config.py
- lithops/localhost/v1/localhost.py
- lithops/localhost/v2/localhost.py
- lithops/tests/conftest.py
> [Localhost] Set v2 as the default localhost backend

- docs/source/storage_config/swift.md
- lithops/storage/backends/swift/swift.py
> Fix Swift authentication by adding domain information

- docs/source/storage_config/ceph.md
- lithops/storage/backends/ceph/ceph.py
> Adds extra region parameter to ceph backend

- CHANGELOG.md
- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- docs/source/compute_config/aws_lambda.md
- lithops/serverless/backends/aws_batch/aws_batch.py
> [AWS] Fix missing ecsTaskJobRole

- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_lambda.md
- lithops/config.py
- lithops/localhost/config.py
- lithops/localhost/v1/localhost.py
- lithops/localhost/v2/localhost.py
> [Standalone] Fix runtime metadata extraction

- docs/source/compute_config/aws_batch.md
- docs/source/compute_config/aws_ec2.md
- lithops/serverless/backends/aws_batch/aws_batch.py
- lithops/serverless/backends/aws_batch/config.py
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
> [AWS] Update docs

- lithops/executors.py
- setup.py
> [Setup] Move matplotlib, seaborn and pandas to 'plotting' extra

- CHANGELOG.md
- lithops/localhost/v1/localhost.py
- lithops/localhost/v2/localhost.py
- lithops/worker/utils.py
> Add error capturing and logging for job/task process failures

- CHANGELOG.md
- lithops/serverless/backends/oracle_f/config.py
> [Oracle Functions] Add support for python 3.11

- lithops/config.py
> [Storage] Fix issue #1378

- lithops/serverless/backends/openwhisk/openwhisk.py
> [OpenWhisk] Fix issue in the list_runtimes method

- lithops/serverless/backends/openwhisk/openwhisk.py
> [OpenWhisk] Fix _unformat_function_name method

- lithops/serverless/backends/aws_lambda/aws_lambda.py
- lithops/serverless/backends/aws_lambda/config.py
Adds user defined tags to the lambda backend.
More support for tagging could be added, but this is a simple, first PR.
> Add user_tags to lambda backend

- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
This PR fixes an issue that appears in the consume mode and the installation script, described #1398  …
> Issue #1398: [Standalone] Fix issue with the installation script

- CHANGELOG.md
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- lithops/standalone/backends/azure_vms/azure_vms.py
- lithops/standalone/backends/ibm_vpc/ibm_vpc.py
- lithops/standalone/keeper.py
- lithops/standalone/master.py
- lithops/standalone/standalone.py
> [Azure VMs] Fixed consume execution mode

- CHANGELOG.md
- lithops/standalone/worker.py
> Issue #1401: [Standalone] Fix issue causing worker to stop prematurely in Consume mode

- CHANGELOG.md
- config/README.md
- docs/source/compute_config/aws_ec2.md
- docs/source/configuration.rst
- docs/source/lithops_config_keys.csv
- lithops/standalone/backends/aws_ec2/aws_ec2.py
- lithops/standalone/backends/aws_ec2/config.py
- Add support for configuring EBS volumes in EC2 lithops workers #1413 
- Add support for specifying CIDR block in EC2 public subnet #1406
(c) The contribution was provided directly to me by …
> [AWS EC2] Add support for configuring EBS volumes in EC2 lithops workers

- lithops/localhost/v1/localhost.py
- lithops/localhost/v2/localhost.py
Potential fix for the file already exists issue in #1438  
it.
(d) I …
> [Localhost] Fix race condition when copying Lithops source to temp dir
